# Programación Entera: Heurísticas para el Problema de la Mochila

#### Descripción

[TODO]

#### Autor
  
  * Sergio García Prado - [garciparedes.me](https://garciparedes.me)
  
#### Fecha

  * Mayo de 2018


## Contenidos
  * [Introducción](#Introducción)
  * [Problema de la Mochila](#Problema-de-la-Mochila)
    * [Mochila Simple](#Mochila-Simple)
    * [Mochila Múltiple](#Mochila-Múltiple)
    * [Mochila Multidimensional](#Mochila-Multidimensional)
  * [Problema de Empaquetamiento](#Problema-de-Empaquetamiento)
  * [Conclusiones](#Conclusiones)

## Introducción

#### Configuración del Entorno

In [1]:
rm(list = ls())

In [2]:
library(slam)
library(Rglpk)
library(magrittr)

Using the GLPK callable library version 4.65


In [3]:
options(repr.matrix.max.rows = 600, repr.matrix.max.cols = 200)

#### Constantes y Funciones de Apoyo

In [4]:
dataset.root <- "./data/"
dataset.folder <- "./data/knapsack/"
dataset.folder.simple <- paste0(dataset.folder, "simple/")
dataset.folder.multi  <- paste0(dataset.folder, "multidimensional/")
dataset.folder.binpacking <- paste0(dataset.root, "binpacking/")

In [5]:
ReadSimpleKnapsack <- function(file.path) {
    con <- 
        file.path %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.double()
    close(con)
    list(
        n = raw[1],
        capacity = raw[2] ,
        value = raw[seq(4, length(raw), by = 3)],
        weight = raw[seq(5, length(raw), by = 3)]
    ) %>%
    return()
}

In [6]:
ReadMultidimensionalKnapsack <- function(file.path) {
    con <- 
        file.path %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.double()
    close(con)
    list(n        = raw[1],
         m        = raw[2],
         objval   = raw[3],
         value    = raw[4:(raw[1]+ 3)],
         weight   = matrix(raw[(4 + raw[1]):(3 + raw[1] * (1 + raw[2]))], 
                           ncol = raw[1], byrow = TRUE),
         capacity = raw[(4 + raw[1] * (1 + raw[2]) ):length(raw)]
    ) %>%
    return()
}

In [7]:
ReadBinPacking <- function(file.path) {
    con <- 
        file.path %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist()
    close(con)
    
    name <- raw[1]
    raw.numeric <- 
        raw[2:length(raw)] %>%
        as.double()

    list(name = name,
         capacity = raw.numeric[1],
         n        = raw.numeric[2],
         objval   = raw.numeric[3],
         size     = raw.numeric[4:length(raw.numeric)]
    ) %>%
    return()
}

In [8]:
Solve <- function(f.obj, f.con, f.dir, f.rhs, ...) {
    Rglpk_solve_LP(f.obj, f.con, f.dir, f.rhs, ...)
}

## Problema de la Mochila

#### Descripción:
TODO

### Mochila Simple

#### Descripción:
TODO

#### Modelo:
TODO

In [9]:
KnapsackSimpleExact <- function(p, types = "B", max = TRUE, ...) {
    Solve(p$value, rbind(matrix(p$weight, nrow = 1, byrow = TRUE), diag(p$n)), 
          rep("<=", length(p$capacity) + p$n), c(p$capacity, rep(1, p$n)), types = types, 
          max = max, ...)
}

#### Heurísticas:
TODO

In [10]:
KnapsackSimpleRounding <- function(p, ...) {
    sol.exact <- KnapsackSimpleExact(p, types = "C", ...)
    
    sol <- list()
    sol$solution = round(sol.exact$solution)
    sol$objval   = sum(sol$solution * p$value)
    sol$slack    = p$capacity - sum(sol$solution * p$weight)
    return(sol)
}

In [11]:
KnapsackSimpleGreedy <- function(p, ...) {
    sol <- list(solution = rep(0, p$n), 
                objval = 0, slack = p$capacity)
    
    i <- which(p$weight == min(p$weight[sol$solution == 0]) & sol$solution == 0)
    i <- i[which.max(p$value[i])][1]
    
    while (sol$slack - p$weight[i] > 0) {
        sol$solution[i] <- 1
        sol$objval <- sol$objval + p$value[i]
        sol$slack <- sol$slack - p$weight[i]
        
        i <- which(p$weight == min(p$weight[sol$solution == 0]) & sol$solution == 0)
        i <- i[which.max(p$value[i])][1]
    }
    return(sol)    
}

In [12]:
KnapsackSimpleLocalSearchBest <- function(p, sol, idx0, idx1) {
    best = list(v = 0, i = 0, j = 0)
    for (i in idx0) {
        for (j in idx1) {
            if (sol$slack + p$weight[j] - p$weight[i] > 0) {
                v.temp <- p$value[i] - p$value[j]
                if(best$v < v.temp) {
                    best$v <- v.temp
                    best$i <- i
                    best$j <- j
                }   
            }
        }
    }
    return(best)
}

In [13]:
KnapsackSimpleLocalSearch <- function(p, ...) {
    sol <- KnapsackSimpleGreedy(p, ...)
    
    idx0 <- which(sol$solution == 0)
    idx1 <- which(sol$solution == 1)
    
    best <- KnapsackSimpleLocalSearchBest(p, sol, idx0, idx1)
    while (best$v > 0) {
        sol$solution[best$i] <- 1
        sol$solution[best$j] <- 0
        sol$slack <- sol$slack + p$weight[best$j] - p$weight[best$i]
        sol$objval <- sol$objval + best$v
        
        idx0 <- c(idx0[idx0 != best$i], best$j)
        idx1 <- c(idx1[idx1 != best$j], best$i)
        
        best <- KnapsackSimpleLocalSearchBest(p, sol, idx0, idx1)
    }
    return(sol)    
}

### Ejemplos

In [14]:
GenerateSimpleKnapsackSolutions <- function(p) {
    sol <- list()
    
    s <- KnapsackSimpleExact(p)
    sol$exact <- list(solution = matrix(s$solution, ncol = p$n, byrow = TRUE),
                      objval   = s$optimum,
                      slack    = p$capacity - s$auxiliary$primal[1])

    s <- KnapsackSimpleExact(p, types = "C")
    sol$relaxed <- list(solution = matrix(s$solution, ncol = p$n, byrow = TRUE),
                        objval   = s$optimum,
                        slack    = p$capacity - s$auxiliary$primal[1])

    s <- KnapsackSimpleRounding(p)
    sol$rounded <- list(solution = matrix(s$solution, ncol = p$n, byrow = TRUE),
                        objval   = s$objval,
                        slack    = s$slack)

    s <- KnapsackSimpleGreedy(p)
    sol$greedy <- list(solution = matrix(s$solution, ncol = p$n, byrow = TRUE),
                       objval   = s$objval,
                       slack    = s$slack)

    s <- KnapsackSimpleLocalSearch(p)
    sol$local <- list(solution = matrix(s$solution, ncol = p$n, byrow = TRUE),
                      objval   = s$objval, 
                      slack    = s$slack)
    
    return(sol)
}

##### gen100.1

In [15]:
gen100.1 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_1.txt"))

In [16]:
GenerateSimpleKnapsackSolutions(gen100.1)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    1    1    1    0    0    0    0     0     0     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     1     0     0     1     0     0     0     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     1     0     0     0     1     0     1     1     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     0     0     0     1     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     1     0     0     1     0     0     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     0     0     0     0     0     1     0     0
     [,99] [,100]
[1,]     1      0

$exact$objval
[1] 1753

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    1    1    1    0    0    0    0     0     0     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0   0.5     0     0     1     0     0     0     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     1     0     0     0     1     0     1     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     0     0     0     1     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     1     0     0     1     0     0     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     1     0     0     0     0     1     0     0
     [,99] [,100]
[1,]     1      0

$relaxed$objval
[1] 1759

$relaxed$slack
[1] 0


$rounded
$rounded$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    1    1    1    0    0    0    0     0     0     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     1     0     0     0     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     1     0     0     0     1     0     1     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     0     0     0     1     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     1     0     0     1     0     0     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     1     0     0     0     0     1     0     0
     [,99] [,100]
[1,]     1      0

$rou

TODO(@garciparedes): Analyze results

##### gen100.2

In [17]:
gen100.2 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_2.txt"))

In [18]:
GenerateSimpleKnapsackSolutions(gen100.2)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    1    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     1     0     0     0     0     1     0     1     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     1     0     0     0     0     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     1     0     0     0     1     0     0     1     0     1     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     0     0     0     1     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     1     0     0     1     0     0     1     0
     [,99] [,100]
[1,]     0      0

$exact$objval
[1] 1744

$exact$slack
[1] 1


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    1    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     1     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     1     0     0     0     0     1     0     1     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     1     0     0     0     0     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     1     0     0     0     1     0     0     1     0     1     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     0     0     0     1     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93]     [,94] [,95] [,96] [,97]
[1,]     0     1     0     0     1     0     0 0.4210526     0     0     1
     [,98] [,99] [,100]
[1,]     0     0      0

$relaxed$objval
[1] 1754.368

$relaxed$slack
[1] 0


$rounded
$rounded$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    1    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     1     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     1     0     0     0     0     1     0     1     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     1     0     0     0     0     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     1     0     0     0     1     0     0     1     0     1     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     0     0     0     1     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     1     0     0     0     0     0     1     0
     [,99] [,100]
[1,]     0 

TODO(@garciparedes): Analyze results

##### gen100.3

In [19]:
gen100.3 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_3.txt"))

In [20]:
GenerateSimpleKnapsackSolutions(gen100.3)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    1    0    0     1     0     1     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     0     0     0     0     1     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     1     0     0     1     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     1     0     0     1     0     0     0     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     0     0     0     0     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     1     1     0     0     1     0     0     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     0     0     1     0     1     0     1     0
     [,99] [,100]
[1,]     0      1

$exact$objval
[1] 1898

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]      [,13]
[1,]    1    0    0    0    0    0    1    0    0     1     0     1 0.07692308
     [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     1     1     1     0     1     0     0     0     0     1     0     0
     [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
[1,]     0     0     0     0     0     1     0     0     1     0     1     0
     [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
[1,]     0     1     0     1     0     0     1     0     0     0     0     0
     [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
[1,]     0     0     0     1     0     0     0     0     0     0     0     0
     [,62] [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     0     1     1     1     0     0     1     0     0     0     0     0
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97]
[1,]     0     0     0     0     0     0     0     1     0     1     0     0
     [,98] [,99] [,100]
[1,]     0     0      1

$relaxed$objval
[1] 1901.846

$relaxed$slack
[1] 0


$rounded
$rounded$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    0    0    1    0    0     1     0     1     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     1     0     1     0     0     0     0     1     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     1     0     0     1     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     1     0     0     1     0     0     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     0     0     0     0     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     1     1     0     0     1     0     0     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     0     0     1     0     1     0     0     0
     [,99] [,100]
[1,]     

TODO(@garciparedes): Analyze results

##### gen100.4

In [21]:
gen100.4 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_4.txt"))

In [22]:
GenerateSimpleKnapsackSolutions(gen100.4)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    1    0    0    0    0    1     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     1     0     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     1     0     0     0     0     0     0     0     0     1     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     0     0     0     1     0     0     1     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     0     0     1     1     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     0     0     0     1     0     0     0     0     0
     [,99] [,100]
[1,]     1      0

$exact$objval
[1] 1825

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    1    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     1     0     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     0     0     0
     [,51] [,52] [,53]     [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
[1,]     1     1     0 0.7333333     0     0     0     0     0     0     1
     [,62] [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     1     0     0     1     0     0     0     0     1     0     0     1
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     1     1     0     0     0     1     0     0     1     1     0     0
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97]
[1,]     0     0     0     1     0     0     0     1     0     0     0     0
     [,98] [,99] [,100]
[1,]     0     1      0

$relaxed$objval
[1] 1826.333

$relaxed$slack
[1] 0


$rounded
$rounded$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    1    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     1     0     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     1     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     1     0     1     0     0     0     0     0     0     1     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     0     0     0     1     0     0     1     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     0     0     1     1     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     0     0     0     1     0     0     0     0     0
     [,99] [,100]
[1,]     1 

TODO(@garciparedes): Analyze results

##### gen100.5

In [23]:
gen100.5 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_5.txt"))

In [24]:
GenerateSimpleKnapsackSolutions(gen100.5)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     0     1     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     0     1     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     1     0     1     0     1     0     0     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     0     0     1     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     1     1     0     0     0     0     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     1     0     0     0     0     1     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     0     0     0     0     1     0     0     0     0
     [,99] [,100]
[1,]     0      0

$exact$objval
[1] 1837

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     1     0     0     0
     [,15]     [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     1 0.3846154     0     1     0     1     0     0     0     0     0
     [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
[1,]     0     0     1     1     1     0     0     0     0     0     0     0
     [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
[1,]     0     1     1     0     1     0     1     0     0     0     0     0
     [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
[1,]     0     0     0     0     0     0     0     0     0     1     0     0
     [,62] [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     0     0     0     1     1     1     0     0     0     0     0     0
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     0     1     0     0     0     1     1     0     0     0     0     1
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97]
[1,]     1     0     0     1     0     0     0     0     1     0     0     0
     [,98] [,99] [,100]
[1,]     0     0      0

$relaxed$objval
[1] 1841.769

$relaxed$slack
[1] 0


$rounded
$rounded$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     0     1     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     1     1     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     1     0     1     0     1     0     0     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     0     0     1     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     1     1     0     0     0     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     1     0     0     0     0     1     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     0     0     0     0     1     0     0     0     0
     [,99] [,100]
[1,]     0 

TODO(@garciparedes): Analyze results

##### gen200.1

In [25]:
gen200.1 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen200_1.txt"))

In [26]:
GenerateSimpleKnapsackSolutions(gen200.1)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    1    1    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     1     0     0     1     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     1     0     0     1     0     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     1     0     0     1     0     1     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     0     0     0     0     0     0     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     1     0     0     1     0     0     1     1     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     1     0     1     1     1     0     0     0     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     1     0     1     1     0     0     0     1     0     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      0      0      1      1      0      0      0      0      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      0      1      0      0      1      0      0      0      0      0
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      1      0      0      0      0      0      0      1      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      0      0      0      0      0      1      0      0      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      0      1      1      1      0      1      1      0      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      1      1      0      0      0      0      0      0      0      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      0      0      0      0      1      0      1      1      0      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      1      1      0      1      1      1      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      1      0      0      0      0      0      1      1      1      0
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      0      1      0      0      1      0      0      0      0
     [,199] [,200]
[1,]      0      1

$exact$objval
[1] 4965

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    1    1    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24]      [,25]
[1,]     1     0     0     0     0     0     0     1     0     0 0.08333333
     [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
[1,]     1     0     0     0     0     1     0     0     1     0     0     1
     [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
[1,]     0     0     0     0     0     1     0     0     1     0     1     0
     [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
[1,]     1     0     0     1     0     0     0     0     0     0     0     0
     [,62] [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     1     1     1     0     0     1     0     0     1     1     0     0
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     0     1     0     0     1     0     1     1     1     0     0     0
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [

##### gen200.2

In [27]:
gen200.2 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen200_2.txt"))

In [28]:
GenerateSimpleKnapsackSolutions(gen200.2)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    1    1    1    0    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     1     1     0     0     1     0     0     0     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     1     0     0     1     0     1     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     0     1     0     0     0     0     0     0     1     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     0     1     1     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     1     0     0     1     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     1     1     0     0     0     1     1     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     1     0     1     0     0     0     1     1     0     0     0     1
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     0      1      0      0      0      1      0      1      0      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      0      0      0      1      0      1      0      1      0      0
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      1      1      0      0      1      0      1      1      0
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      0      0      1      0      1      0      0      0      1      0
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      0      0      0      0      0      0      0      0      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      1      1      1      0      1      0      0      0      0      1
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      1      1      0      0      0      0      0      0      0      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      1      1      0      1      0      1      0      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      1      0      0      1      1      1      0      0      1      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      1      0      0      0      0      0      0      0      0      1
     [,199] [,200]
[1,]      0      0

$exact$objval
[1] 4961

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    1    1    1    0    1     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     1     1     0     0     1     0     0     0     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     1     0     1     1     0     1     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     1     0     0     0     0     0     0     1     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     0     1     1     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     1     0     0     1     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     1     1     0     0     0     1     1     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93]

TODO(@garciparedes): Analyze results

##### gen200.3

In [29]:
gen200.3 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen200_3.txt"))

In [30]:
GenerateSimpleKnapsackSolutions(gen200.3)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    1    1    0    1    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     1     1     0     1     0     0     1     0     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     1     0     1     0     1     1     0     0     1     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     0     0     0     0     0     0     0     1     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     1     0     1     1     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     0     0     0     1     1     0     1     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     1     0     0     0     0     0     0     1     1     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     1     0     0     0     0     1     0     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      1      0      0      1      0      0      1      1      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      0      0      0      0      1      0      0      0      0      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      0      0      0      0      0      0      0      0      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      0      1      0      1      0      1      1      1      0
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      0      1      0      0      0      1      0      0      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      0      1      0      0      0      0      0      0      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      0      0      1      1      1      0      1      1      0      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      1      0      1      0      0      1      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      1      1      0      1      1      0      0      0      1      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      0      0      0      1      1      1      0      0      0
     [,199] [,200]
[1,]      0      0

$exact$objval
[1] 5232

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    1    1    0    1    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     1     1     0     1     0     0     1     0     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     1     0     1     0     1     1     0     0     1     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     0     0     0     0     0     0     0     1     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     1     0     1     1     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67]     [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     0     0     0     0     0 0.1333333     1     0     1     0     0
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     1     0     1     0     0     0     0     0     0     1     1     0
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [,9

TODO(@garciparedes): Analyze results

##### gen200.4

In [31]:
gen200.4 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen200_4.txt"))

In [32]:
GenerateSimpleKnapsackSolutions(gen200.4)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    0    0    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     1     0     0     0     0     1     0     0     0     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     0     0     0     1     0     0     0     0     1     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     0     0     1     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     1     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     1     1     0     0     0     1     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     0     0     1     1     0     1     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     1     0     0     1     1     0     0     0     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      0      1      0      0      1      0      0      1      1
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      0      1      1      0      1      1      0      1      0      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      1      0      1      1      0      0      1      0      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      0      0      0      0      1      0      0      0      0      0
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      1      1      1      0      0      0      0      0      1
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      0      1      0      0      1      0      0      0      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      1      0      0      0      1      0      0      1      1      1
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      0      0      0      1      1      0      0      1
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      1      0      1      0      0      0      0      0      0      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      1      0      1      1      1      1      0      0      0      0
     [,199] [,200]
[1,]      0      0

$exact$objval
[1] 4971

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    0    0    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     1     0     0     0     0     1     0     0     0     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     0     0     0     1     0     0     0     0     1     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     0     0     0     1     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     1     0     0     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     1     1     1     0     0     0     1     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     0     0     1     1     0     1     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93]

TODO(@garciparedes): Analyze results

##### gen200.5

In [33]:
gen200.5 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen200_5.txt"))

In [34]:
GenerateSimpleKnapsackSolutions(gen200.5)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    0    1    0    0    1    1     0     0     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     1     1     0     0     1     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     1     0     0     0     1     1     0     1     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     1     1     1     0     0     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     1     0     0     0     1     0     1     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     1     0     0     0     0     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     0     0     0     0     1     1     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     0     0     0     0     0     0     1     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      1      0      0      1      0      0      0      0      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      1      0      0      1      1      1      0      0      0      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      1      1      0      0      0      1      0      0      0      0
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      0      0      0      0      1      1      0      1      1      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      1      0      0      0      1      0      0      0      0      1
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      0      0      0      0      1      0      1      0      1
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      1      0      0      1      0      1      0      0      0      1
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      0      1      0      0      0      0      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      0      0      0      0      1      0      0      0      1      0
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      1      1      0      0      0      0      1      0      0
     [,199] [,200]
[1,]      0      1

$exact$objval
[1] 5031

$exact$slack
[1] 0


$relaxed
$relaxed$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7]      [,8] [,9] [,10] [,11] [,12] [,13]
[1,]    0    1    0    0    1    0    0 0.6666667    1     0     0     1     0
     [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     0     1     0     0     1     1     1     0     0     1     0     0
     [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
[1,]     0     1     0     1     0     0     0     1     1     0     1     1
     [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
[1,]     0     0     0     0     1     1     1     0     0     0     0     0
     [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61]
[1,]     0     0     0     1     1     0     0     0     1     0     1     0
     [,62] [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73]
[1,]     0     0     0     1     0     1     0     0     0     0     0     0
     [,74] [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85]
[1,]     1     0     0     0     0     0     0     0     1     1     0     1
     [,86] [,87] [,88] [,89] [,90] [,91] [,92] [

TODO(@garciparedes): Analyze results

##### gen300.1

In [35]:
gen300.1 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen300_1.txt"))

In [36]:
GenerateSimpleKnapsackSolutions(gen300.1)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    0    1    1    0    0    0     0     0     0     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     1     1     1     1     1     1     0     0     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     0     0     1     0     1     0     0     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     1     0     0     1     0     1     0     0     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     1     1     1     0     1     1     1     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     0     1     1     1     1     1     1     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     1     0     1     1     0     1     0     0     1     0     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     1     1     0     1     1     0     0     1     1     0     0     1
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     0      0      0      1      1      1      0      0      0      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      1      1      1      1      0      1      1      0      1      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      1      0      0      0      1      1      0      1      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      1      1      0      1      0      1      0      1      0
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      0      0      1      0      0      1      0      0      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      0      0      1      0      1      0      0      1      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      0      1      0      0      0      1      0      0      1      1
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      1      0      1      1      1      0      1      0      1      1
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      0      0      1      0      0      0      0      0      0      0
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      1      1      1      0      1      1      1      1      1      1
     [,199] [,200] [,201] [,202] [,203] [,204] [,205] [,206] [,207] [,208]
[1,]      0      1      0      1      1      1      1      1      0      0
     [,209] [,210] [,211] [,212] [,213] [,214] [,215] [,216] [,217] [,218]
[1,]      1      0      1      1      0      0      0      1      0      1
     [,219] [,220] [,221] [,222] [,223] [,224] [,225] [,226] [,227] [,228]
[1,]      0      0      0      0      0      1      1      0      1      1
     [,229] [,230] [,231] [,232] [,233] [,234] [,235] [,236] [,237] [,238]
[1,]      0      1      1      1      1      0      0      0      0      1
     [,239] [,240] [,241] [,242] [,243] [,244] [,245] [,246] [,247] [,248]
[1,]      1      0      1      0      1      1      1      0      0      1
     [,249] [,250] [,251] [,252] [,253] [,254] [,255] [,256] [,257] [,258]
[1,]      1      1      0      1      0      0      0      1      0      1
     [,259] [,260] [,261] [,262] [,263] [,264] [,265] [,266] [,267] [,268]
[1,]      1      1      1      1      1      1      1      0      1      1
     [,269] [,270] [,271] [,272] [,273] [,274] [,275] [,276] [,277] [,278]
[1,]      1      0      1      0      1      0      1      0      0      1
     [,279] [,280] [,281] [,282] [,283] [

TODO(@garciparedes): Analyze results

##### gen300.2

In [37]:
gen300.2 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen300_2.txt"))

In [38]:
GenerateSimpleKnapsackSolutions(gen300.2)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    1    0    1    0    1    1     0     0     1     1     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     1     1     0     0     0     0     1     0     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     1     1     1     0     1     1     1     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     1     1     1     1     1     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     0     0     0     1     1     1     0     1     1     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     1     1     1     1     0     1     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     1     0     1     0     1     1     0     0     1     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     1     0     1     1     1     1     1     0     1
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      1      0      0      1      1      1      1      0      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      0      1      1      0      1      0      0      0      0      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      0      0      1      0      1      0      1      1      0      0
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      0      1      0      1      0      1      0      0      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      1      0      0      1      0      1      0      1      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      1      1      0      1      1      1      0      0      0      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      1      1      1      0      0      0      0      1      1      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      0      1      1      1      1      1      0      1
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      0      1      0      1      1      0      1      1      0      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      1      1      1      1      1      1      1      0      1
     [,199] [,200] [,201] [,202] [,203] [,204] [,205] [,206] [,207] [,208]
[1,]      0      1      1      0      1      1      0      0      1      1
     [,209] [,210] [,211] [,212] [,213] [,214] [,215] [,216] [,217] [,218]
[1,]      1      0      0      0      0      1      0      1      1      1
     [,219] [,220] [,221] [,222] [,223] [,224] [,225] [,226] [,227] [,228]
[1,]      1      1      1      1      0      1      0      1      0      1
     [,229] [,230] [,231] [,232] [,233] [,234] [,235] [,236] [,237] [,238]
[1,]      0      0      1      0      1      1      0      1      0      0
     [,239] [,240] [,241] [,242] [,243] [,244] [,245] [,246] [,247] [,248]
[1,]      0      0      1      1      1      0      1      1      1      1
     [,249] [,250] [,251] [,252] [,253] [,254] [,255] [,256] [,257] [,258]
[1,]      1      0      0      1      1      1      0      0      0      1
     [,259] [,260] [,261] [,262] [,263] [,264] [,265] [,266] [,267] [,268]
[1,]      0      1      0      1      0      1      1      1      1      0
     [,269] [,270] [,271] [,272] [,273] [,274] [,275] [,276] [,277] [,278]
[1,]      0      1      1      0      0      1      1      0      1      1
     [,279] [,280] [,281] [,282] [,283] [

TODO(@garciparedes): Analyze results

##### gen300.3

In [39]:
gen300.3 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen300_3.txt"))

In [40]:
GenerateSimpleKnapsackSolutions(gen300.3)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    1    0    1    0    0    1    1     1     0     1     1     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     1     1     1     0     1     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     1     0     1     0     0     0     1     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     1     0     0     1     0     1     1     1     1     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     1     1     1     1     1     0     0     1     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     1     0     1     1     0     0     0     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     1     0     0     0     1     1     1     0     1     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     1     0     1     0     1     1     0     1     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      1      1      1      0      1      1      0      0      1
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      1      1      0      1      0      1      1      0      1      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      1      1      1      1      1      0      0      0      0      0
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      0      0      0      1      0      1      1      1      1      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      0      0      0      0      0      0      1      1      1
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      1      0      1      1      0      0      1      0      1      0
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      0      1      0      1      0      1      1      0      1      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      0      0      0      0      0      1      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      0      1      0      0      0      1      1      1      1      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      1      0      0      1      0      1      0      0      1
     [,199] [,200] [,201] [,202] [,203] [,204] [,205] [,206] [,207] [,208]
[1,]      0      1      0      0      0      1      1      1      1      1
     [,209] [,210] [,211] [,212] [,213] [,214] [,215] [,216] [,217] [,218]
[1,]      1      1      1      1      1      1      1      0      1      0
     [,219] [,220] [,221] [,222] [,223] [,224] [,225] [,226] [,227] [,228]
[1,]      0      0      0      1      0      0      0      1      0      0
     [,229] [,230] [,231] [,232] [,233] [,234] [,235] [,236] [,237] [,238]
[1,]      1      0      0      0      1      1      1      1      0      0
     [,239] [,240] [,241] [,242] [,243] [,244] [,245] [,246] [,247] [,248]
[1,]      1      1      0      1      1      1      1      1      1      0
     [,249] [,250] [,251] [,252] [,253] [,254] [,255] [,256] [,257] [,258]
[1,]      0      1      1      1      0      1      1      0      1      0
     [,259] [,260] [,261] [,262] [,263] [,264] [,265] [,266] [,267] [,268]
[1,]      1      0      1      1      0      0      0      1      1      1
     [,269] [,270] [,271] [,272] [,273] [,274] [,275] [,276] [,277] [,278]
[1,]      1      1      1      0      0      1      0      0      0      1
     [,279] [,280] [,281] [,282] [,283] [

TODO(@garciparedes): Analyze results

##### gen300.4

In [41]:
gen300.4 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen300_4.txt"))

In [42]:
GenerateSimpleKnapsackSolutions(gen300.4)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    1    1    0    0    0    0    0     1     1     0     1     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     1     1     1     0     1     0     0     1     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     1     0     1     1     0     0     0     0     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     0     1     1     0     0     0     0     0     0     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     1     0     1     0     0     0     1     0     1     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     1     0     1     1     1     1     0     1     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     0     0     0     0     0     1     1     0     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     1     1     0     0     1     0     0     1     0     0     0     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      0      0      0      0      0      1      0      0      1
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      1      0      1      0      0      0      1      1      1      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      1      0      0      0      0      0      1      1      1      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      1      0      0      0      0      1      1      1      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      0      1      0      0      0      1      1      1      1      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      1      0      1      0      1      0      0      0      1
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      1      1      1      0      0      0      0      1      1      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      1      0      1      0      0      1      1      1      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      1      1      0      1      1      1      1      0      1      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      0      1      1      0      0      0      0      1      1      0
     [,199] [,200] [,201] [,202] [,203] [,204] [,205] [,206] [,207] [,208]
[1,]      1      1      1      0      0      0      1      1      1      0
     [,209] [,210] [,211] [,212] [,213] [,214] [,215] [,216] [,217] [,218]
[1,]      1      1      0      0      1      0      1      1      1      1
     [,219] [,220] [,221] [,222] [,223] [,224] [,225] [,226] [,227] [,228]
[1,]      0      1      0      1      0      0      0      1      1      1
     [,229] [,230] [,231] [,232] [,233] [,234] [,235] [,236] [,237] [,238]
[1,]      0      1      0      1      1      1      0      0      0      1
     [,239] [,240] [,241] [,242] [,243] [,244] [,245] [,246] [,247] [,248]
[1,]      1      1      1      1      1      1      1      0      1      1
     [,249] [,250] [,251] [,252] [,253] [,254] [,255] [,256] [,257] [,258]
[1,]      1      1      1      0      1      0      1      1      1      1
     [,259] [,260] [,261] [,262] [,263] [,264] [,265] [,266] [,267] [,268]
[1,]      0      0      1      1      1      1      0      1      1      1
     [,269] [,270] [,271] [,272] [,273] [,274] [,275] [,276] [,277] [,278]
[1,]      0      0      1      1      0      1      1      1      1      0
     [,279] [,280] [,281] [,282] [,283] [

TODO(@garciparedes): Analyze results

##### gen300.5

In [43]:
gen300.5 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen300_5.txt"))

In [44]:
GenerateSimpleKnapsackSolutions(gen300.5)

$exact
$exact$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    1    1    0    0    0    1    1     1     1     1     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     1     1     0     1     1     0     0     0     1     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     1     0     0     1     0     1     0     1     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     0     1     1     1     0     0     1     0     0     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     0     1     1     0     1     1     1     1     0     0     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     1     1     1     0     1     1     1     1     1     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     1     0     1     1     1     1     0     1     1     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     1     1     1     0     0     0     1     0     0
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,]     1      1      0      1      1      1      0      1      1      0
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,]      1      0      1      1      1      1      0      0      0      1
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,]      1      0      0      1      0      0      1      0      0      1
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,]      1      1      0      0      0      1      0      1      1      1
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,]      1      1      0      1      1      0      1      1      0      0
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,]      0      1      1      0      0      0      1      0      1      1
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,]      0      0      1      1      0      0      1      0      0      0
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,]      0      0      1      1      0      0      0      0      0      0
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,]      0      0      1      1      1      0      0      0      1      1
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,]      1      0      0      1      1      1      1      0      1      1
     [,199] [,200] [,201] [,202] [,203] [,204] [,205] [,206] [,207] [,208]
[1,]      1      1      0      1      1      0      1      1      1      1
     [,209] [,210] [,211] [,212] [,213] [,214] [,215] [,216] [,217] [,218]
[1,]      0      0      0      1      0      1      1      0      1      0
     [,219] [,220] [,221] [,222] [,223] [,224] [,225] [,226] [,227] [,228]
[1,]      0      1      0      1      1      0      0      0      1      1
     [,229] [,230] [,231] [,232] [,233] [,234] [,235] [,236] [,237] [,238]
[1,]      1      1      0      0      0      1      0      0      0      1
     [,239] [,240] [,241] [,242] [,243] [,244] [,245] [,246] [,247] [,248]
[1,]      0      0      0      1      1      0      1      1      0      1
     [,249] [,250] [,251] [,252] [,253] [,254] [,255] [,256] [,257] [,258]
[1,]      1      0      1      1      1      1      0      1      0      0
     [,259] [,260] [,261] [,262] [,263] [,264] [,265] [,266] [,267] [,268]
[1,]      0      1      0      0      0      1      1      1      1      1
     [,269] [,270] [,271] [,272] [,273] [,274] [,275] [,276] [,277] [,278]
[1,]      1      0      0      0      1      1      1      0      0      0
     [,279] [,280] [,281] [,282] [,283] [

TODO(@garciparedes): Analyze results

### Mochila Múltiple

#### Descripción:
TODO

#### Modelo:
TODO

In [45]:
KnapsackMultipleExact <- function(p, m, ...) {
    conditions <- matrix(rep(0,(m + p$n) * p$n * m), 
                         nrow = m + p$n, ncol = p$n * m, byrow = TRUE)
    
    for(i in 1:m) {
        conditions[i, (i - 1) * p$n + 1:p$n] <- p$weight
    }
    for(i in (m + 1):(p$n + m)) {
        conditions[i, seq(i-m, p$n*m, by = p$n)] <- 1
    }

    Solve(rep(p$value, m), conditions, 
          c(rep("<=", m), rep("<=", p$n)),
          c(rep(p$capacity, m), rep(1, p$n)),
                 types = "B", max = TRUE, ...)
}

#### Heurísticas:
TODO

In [46]:
KnapsackMultipleGreedy <- function(object, capacity) {
    
}

### Ejemplos

In [47]:
gen10.1 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen10_1.txt"))
m <- 3
s <- KnapsackMultipleExact(gen10.1, m)
list(solution = matrix(s$solution, ncol = gen10.1$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    1    1    1    0    1    0    0     0     1     1     0     0
[2,]    0    0    0    0    0    0    0    0    1     1     0     0     1     1
[3,]    0    0    0    0    0    1    0    1    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     1     0     0     0     0     0     0     1
[2,]     0     1     0     0     0     0     1     1     1     1     1     0
[3,]     0     0     1     1     0     1     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     0     0     0     1     0     1     1     1     1     0
[2,]     1     0     1     1     1     0     1     0     0     0     0     0
[3,]     0     0     0     0     0     0     0     0     0     0     0     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     0     1     1     0     1     0     0
[2,]     0     1     1     0     1     1     0     0     0     0     0     1
[3,]     1     0     0     1     0     0     0     0     0     0     1     0

$objval
[1] 2286

In [48]:
gen100.1 <- ReadSimpleKnapsack(paste0(dataset.folder.simple, "gen100_1.txt"))

In [49]:
# m <- 3
# s <- KnapsackMultipleExact(gen100.1, m)
# list(solution = matrix(s$solution, ncol = gen100.1$n, byrow = TRUE),
#      objval = s$optimum)

##### gen100.1

##### gen100.2

##### gen100.3

##### gen100.4

##### gen100.5

##### gen200.1

##### gen200.2

##### gen200.3

##### gen200.4

##### gen200.5

##### gen300.1

##### gen300.2

##### gen300.3

##### gen300.4

##### gen300.5

### Mochila Multidimensional

#### Descripción:
TODO

#### Modelo:
TODO

In [50]:
KnapsackMultidimensionalExact <- function(p, ...) {    
    Solve(p$value, p$weight, rep("<=", length(p$capacity)), 
          p$capacity, types = "B", max = TRUE, ...)
}

#### Heurísticas:
TODO

In [51]:
KnapsackMultidimensionalGreedy <- function(object, capacity) {
    
}

### Ejemplos

##### mknap1.2

In [52]:
mknap1.2 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknap1_2.dat"))

In [53]:
s <- KnapsackMultidimensionalExact(mknap1.2)
list(solution = matrix(s$solution, ncol = mknap1.2$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    0    1    0    1    1    0    0    1    0     1

$objval
[1] 8706.1

##### mknap1.3

In [54]:
mknap1.3 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknap1_3.dat"))

In [55]:
s <- KnapsackMultidimensionalExact(mknap1.3)
list(solution = matrix(s$solution, ncol = mknap1.3$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    1    0    1    1    0    1     1     0     0     0     1
     [,15]
[1,]     1

$objval
[1] 4015

##### mknap1.4

In [56]:
mknap1.4 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknap1_4.dat"))

In [57]:
s <- KnapsackMultidimensionalExact(mknap1.4)
list(solution = matrix(s$solution, ncol = mknap1.4$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    0    0    0    0    0     1     0     0     0     1
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]     1     1     1     1     1     1

$objval
[1] 6120

##### mknap1.6

In [58]:
mknap1.6 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknap1_6.dat"))

In [59]:
s <- KnapsackMultidimensionalExact(mknap1.6)
list(solution = matrix(s$solution, ncol = mknap1.6$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    1    0    1    0    1    1     0     1     0     1     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     1     1     1     1     1     0     0     1     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     1     1     0     1     1     0     1     1     1     1     1
     [,39]
[1,]     1

$objval
[1] 10618

##### mknap1.7

In [60]:
mknap1.7 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknap1_7.dat"))

In [61]:
s <- KnapsackMultidimensionalExact(mknap1.7)
list(solution = matrix(s$solution, ncol = mknap1.7$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    1    0    1    0    1    1     0     1     1     1     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     1     1     0     1     1     0     0     1     0     1     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     1     1     0     1     1     0     1     1     1     1     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     1     1     1     1     1     1     0     0     1     1     1     1

$objval
[1] 16537

##### mknapcb1.1

In [62]:
mknapcb1.1 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknapcb1_1.dat"))

In [63]:
s <- KnapsackMultidimensionalExact(mknapcb1.1)
list(solution = matrix(s$solution, ncol = mknapcb1.1$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    1    0    0    1    0    1     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     0     0     0     0     1     0     1
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     1     1     0     1     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     0     1     0     0     0     0     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     0     0     0     1     0     0     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     0     0     1     0     1     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     1     0     1     0     0     0     0     0     1     1
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     0     0     0     1     1     0     0     1     0     0
     [,99] [,100]
[1,]     1      0

$objval
[1] 24381

##### mknapcb1.2

In [64]:
mknapcb1.2 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknapcb1_2.dat"))

In [65]:
s <- KnapsackMultidimensionalExact(mknapcb1.2)
list(solution = matrix(s$solution, ncol = mknapcb1.2$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    1    0    0    0    0    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     0     1     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     1     0     0     0     0     0     1     0     1     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     1     1     0     0     1     0     0     1     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     1     0     0     1     1     1     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     1     0     0     0     0     0     0     0     0     1
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     0     0     0     1     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     0     1     0     1     1     0     1     0     1     0     0
     [,99] [,100]
[1,]     0      1

$objval
[1] 24274

##### mknapcb1.3

In [66]:
mknapcb1.3 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknapcb1_3.dat"))

In [67]:
s <- KnapsackMultidimensionalExact(mknapcb1.3)
list(solution = matrix(s$solution, ncol = mknapcb1.3$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    1    0    0    0    0     0     0     1     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     1     1     0     1     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     1     0     1     0     0     0     1     0     1     0     0     1
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     1     0     1     0     0     0     1     0
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     1     0     0     0     1     0     0     0     1     1     0
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     0     1     0     0     0     0     0     0     0     1     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     1     0     0     0     0     1     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     0     0     1     1     0     0     1     0
     [,99] [,100]
[1,]     0      1

$objval
[1] 23551

##### mknapcb1.4

In [68]:
mknapcb1.4 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknapcb1_4.dat"))

In [69]:
s <- KnapsackMultidimensionalExact(mknapcb1.4)
list(solution = matrix(s$solution, ncol = mknapcb1.4$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    1    0    1    0    0    1     0     0     1     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     1     0     1     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     1     0     0     1     0     0     0     1     1     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     0     0     1     0     0     0     0     0     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     0     0     0     1     1     1     1     0     1     0     0     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     0     1     0     0     0     0     0     0     0     0     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     1     0     0     0     1     1     0     0     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     1     0     0     0     0     0     0     0     1     1     0     0
     [,99] [,100]
[1,]     0      0

$objval
[1] 23534

##### mknapcb1.5

In [70]:
mknapcb1.5 <- ReadMultidimensionalKnapsack(paste0(dataset.folder.multi, "mknapcb1_5.dat"))

In [71]:
s <- KnapsackMultidimensionalExact(mknapcb1.5)
list(solution = matrix(s$solution, ncol = mknapcb1.5$n, byrow = TRUE),
     objval = s$optimum)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    0    1    0    0    0    1     0     0     0     0     1
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     1     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     1     0     0     0     0     0     1     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,]     0     0     1     0     0     0     1     0     1     0     0     1
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,]     1     0     0     0     1     1     1     0     0     0     1     1
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,]     1     0     0     1     1     1     0     0     0     1     0     0
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,]     0     0     0     0     0     1     0     1     0     0     0     0
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,]     0     1     0     0     0     0     1     0     0     1     1     0
     [,99] [,100]
[1,]     1      1

$objval
[1] 23991

## Problema de Empaquetamiento

#### Descripción:
TODO

### Empaquetamiento Unidimensional

#### Descripción:
TODO

#### Modelo:
TODO

In [72]:
OneDimBinPackingExact <- function(p, ...) {    
    
}

#### Heurísticas:
TODO

In [73]:
OneDimBinPackingGreedy <- function(object, capacity) {
    
}

### Ejemplos

##### u120.00

In [74]:
u120.00 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u120_00.dat"))

##### u120.01

In [75]:
u120.01 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u120_01.dat"))

##### u120.02

In [76]:
u120.02 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u120_02.dat"))

##### u250.00

In [77]:
u250.00 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u250_00.dat"))

##### u250.01

In [78]:
u250.01 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u250_01.dat"))

##### u250.02

In [79]:
u250.02 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u250_02.dat"))

##### u500.00

In [80]:
u500.00 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u500_00.dat"))

##### u500.01

In [81]:
u500.01 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u500_01.dat"))

##### u500.02

In [82]:
u500.02 <- ReadBinPacking(paste0(dataset.folder.binpacking, "u500_02.dat"))

## Conclusiones