# Programación Entera: Heurísticas para el Problema de la Mochila

## Descripción

[TODO]

## Autor
  
  * Sergio García Prado - [garciparedes.me](https://garciparedes.me)
  
## Fecha

  * Mayo de 2018


## Contenidos
  * [Problema de la Mochila](#Problema-de-la-Mochila)
    * [Mochila Simple](#Mochila-Simple)
    * [Mochila Múltiple](#Mochila-Múltiple)
    * [Mochila Multidimensional](#Mochila-Multidimensional)

In [1]:
library(lpSolve)
library(magrittr)

In [2]:
options(repr.matrix.max.rows = 600, repr.matrix.max.cols = 200)

## Funciones de Apoyo

In [3]:
dataset.folder <- "./data"

In [4]:
ReadDataSet <- function() {
    
}

In [5]:
Solve <- function(direction = "max", f.obj, f.con, f.rhs, f.dir = rep("<=", nrow(f.con)), ...) {
    lp(direction, f.obj, f.con, f.dir, f.rhs, ...)
}

## Problema de la Mochila

#### Descripción:
TODO

### Mochila Simple

#### Descripción:
TODO

In [6]:
ReadSimpleKnapsack <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.integer()
    close(con)
    list(
        n = raw[1],
        capacity = raw[2] ,
        value = raw[seq(4, length(raw), by = 3)],
        weight = raw[seq(5, length(raw), by = 3)]
    ) %>%
    return()
}

#### Modelo:
TODO

In [7]:
KnapsackSimpleExact <- function(p, ...) {
    return(Solve("max", p$value, matrix(p$weight, nrow = 1, byrow = TRUE), p$capacity, 
                 all.bin = TRUE, ...))    
}

#### Heurísticas:
TODO

In [8]:
KnapsackSimpleGreedy <- function(p, ...) {
    
}

### Ejemplos

In [9]:
gen100.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_1.txt")

In [10]:
a <- KnapsackSimpleExact(gen100.1)
matrix(a$solution, ncol = gen100.1$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    0    1    1    1    0    0    0    0    0     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     0     0     0     0     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     1     0     0     1     0     0     0     0     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     0     0     1     0     1     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     1     0     0     0     1     0     1     1     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     0     1     0     0     0     1     0     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     1     0     0     1     0     0     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     0     0     0     0     0     0     1     0     0    
     [,99] [,100]
[1,] 1     0

[1] 1753

In [11]:
gen100.2 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_2.txt")

In [12]:
a <- KnapsackSimpleExact(gen100.2)
matrix(a$solution, ncol = gen100.2$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    1    1    0    0    0     0     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     1     0     0     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     1     0     0     0     0     0     0     0     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     1     1     0     0     0     0     1     0     1     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     0     1     0     0     0     0     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     1     0     0     0     1     0     0     1     0     1     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     0     0     0     1     0     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     0     1     0     0     1     0     0     1     0    
     [,99] [,100]
[1,] 0     0

[1] 1744

In [13]:
gen100.3 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_3.txt")

In [14]:
a <- KnapsackSimpleExact(gen100.3)
matrix(a$solution, ncol = gen100.3$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    1    0    0    1     0     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     0     0     0     0     1     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     0     1     0     0     1     0     1     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     0     1     0     0     1     0     0     0     1     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     1     0     0     0     0     0     0     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     0     0     0     0     0     0     0     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     1     1     0     0     1     0     0     0     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     0     0     0     1     0     1     0     1     0    
     [,99] [,100]
[1,] 0     1

[1] 1898

In [15]:
gen100.4 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_4.txt")

In [16]:
a <- KnapsackSimpleExact(gen100.4)
matrix(a$solution, ncol = gen100.4$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    1    0    1    0    0    0    0    1    0     0     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     0     0     0     0     0     0     0     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     0     0     0     1     0     0     1     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     0     0     1     0     0     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 1     1     0     0     0     0     0     0     0     0     1     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     0     0     0     0     1     0     0     1     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     1     0     0     1     1     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     1     0     0     0     1     0     0     0     0     0    
     [,99] [,100]
[1,] 1     0

[1] 1825

In [17]:
gen100.5 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_5.txt")

In [18]:
a <- KnapsackSimpleExact(gen100.5)
matrix(a$solution, ncol = gen100.5$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    0    0    0    0     1     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     0     1     0     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     1     0     1     0     0     0     0     0     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     1     0     1     0     1     0     0     0     0     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     0     0     0     0     0     1     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     1     1     0     0     0     0     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     1     1     0     0     0     0     1     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     1     0     0     0     0     1     0     0     0     0    
     [,99] [,100]
[1,] 0     0

[1] 1837

In [19]:
gen200.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen200_1.txt")

In [20]:
a <- KnapsackSimpleExact(gen200.1)
matrix(a$solution, ncol = gen200.1$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    1    1    0    1     0     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     0     0     0     0     1     0     0     1     1    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     0     1     0     0     1     0     0     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     1     0     0     1     0     1     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     1     0     0     0     0     0     0     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     1     0     0     1     0     0     1     1     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     1     0     1     1     1     0     0     0     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     1     0     1     1     0     0     0     1     0     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     0      0      1      1      0      0      0      0      0     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      1      0      0      1      0      0      0      0      0     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      1      0      0      0      0      0      0      1      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      0      0      0      0      0      1      0      0      1     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      0      1      1      1      0      1      1      0      0     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      0      0      0      0      0      0      0      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 0      0      0      0      1      0      1      1      0      0     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      0      1      1      0      1      1      1      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      0      0      0      0      0      1      1      1      0     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      0      1      0      0      1      0      0      0      0     
     [,199] [,200]
[1,] 0      1

[1] 4965

In [21]:
gen200.2 <- ReadSimpleKnapsack("./data/knapsack/simple/gen200_2.txt")

In [22]:
a <- KnapsackSimpleExact(gen200.2)
matrix(a$solution, ncol = gen200.2$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    1    1    1    0    0    0     1     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     1     1     0     0     1     0     0     0     1     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     1     0     0     1     0     1     1     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     0     0     1     0     0     0     0     0     0     1     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     0     0     0     0     1     1     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     0     1     0     0     1     0     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     1     1     0     0     0     1     1     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 1     0     1     0     0     0     1     1     0     0     0     1    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 0     1      0      0      0      1      0      1      0      0     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      0      0      1      0      1      0      1      0      0     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      1      1      0      0      1      0      1      1      0     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 0      0      1      0      1      0      0      0      1      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      0      0      0      0      0      0      0      0      0     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      1      0      1      0      0      0      0      1     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      1      0      0      0      0      0      0      0      0     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      1      1      0      1      0      1      0      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      0      0      1      1      1      0      0      1      1     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 1      0      0      0      0      0      0      0      0      1     
     [,199] [,200]
[1,] 0      0

[1] 4961

In [23]:
gen200.3 <- ReadSimpleKnapsack("./data/knapsack/simple/gen200_3.txt")

In [24]:
a <- KnapsackSimpleExact(gen200.3)
matrix(a$solution, ncol = gen200.3$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    0    0    0    1    1    0    1    0    0     0     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     1     1     0     1     0     0     1     0     0     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     1     0     1     0     1     1     0     0     1     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     1     0     0     0     0     0     0     0     1     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     1     1     0     1     1     0     0     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     0     0     0     1     1     0     1     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     1     0     0     0     0     0     0     1     1     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     0     1     0     0     0     0     1     0     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     1      0      0      1      0      0      1      1      0     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      0      0      0      1      0      0      0      0      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      0      0      0      0      0      0      0      0      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      0      1      0      1      0      1      1      1      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      0      1      0      0      0      1      0      0      0     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 0      0      1      0      0      0      0      0      0      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 0      0      1      1      1      0      1      1      0      0     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      0      1      0      1      0      0      1      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      1      0      1      1      0      0      0      1      1     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      0      0      0      1      1      1      0      0      0     
     [,199] [,200]
[1,] 0      0

[1] 5232

In [25]:
gen200.4 <- ReadSimpleKnapsack("./data/knapsack/simple/gen200_4.txt")

In [26]:
a <- KnapsackSimpleExact(gen200.4)
matrix(a$solution, ncol = gen200.4$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    1    0    0    0    1     0     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     1     0     0     0     0     1     0     0     0     1    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     0     0     0     0     1     0     0     0     0     1     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     0     0     0     0     1     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     0     0     0     1     0     0     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     1     1     1     0     0     0     1     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     0     0     1     1     0     1     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     1     0     0     1     1     0     0     0     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     0      1      0      0      1      0      0      1      1     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      0      1      0      1      1      0      1      0      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      1      0      1      1      0      0      1      0      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 0      0      0      0      1      0      0      0      0      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      1      1      1      0      0      0      0      0      1     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 0      0      1      0      0      1      0      0      0      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      0      0      0      1      0      0      1      1      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      0      0      0      0      1      1      0      0      1     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      0      1      0      0      0      0      0      0      1     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 1      0      1      1      1      1      0      0      0      0     
     [,199] [,200]
[1,] 0      0

[1] 4971

In [27]:
gen200.5 <- ReadSimpleKnapsack("./data/knapsack/simple/gen200_5.txt")

In [28]:
a <- KnapsackSimpleExact(gen200.5)
matrix(a$solution, ncol = gen200.5$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    1    0    0    1    0    0    1    1    0     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     1     1     0     0     1     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     0     1     0     0     0     1     1     0     1     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     1     1     1     0     0     0     0     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     1     1     0     0     0     1     0     1     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     0     1     0     0     0     0     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     0     0     0     0     1     1     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     0     0     0     0     0     0     0     1     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     1      0      0      1      0      0      0      0      0     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 1      0      0      1      1      1      0      0      0      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 1      1      0      0      0      1      0      0      0      0     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 0      0      0      0      1      1      0      1      1      1     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 1      0      0      0      1      0      0      0      0      1     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 0      0      0      0      0      1      0      1      0      1     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      0      0      1      0      1      0      0      0      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      0      0      1      0      0      0      0      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 0      0      0      0      1      0      0      0      1      0     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      1      1      0      0      0      0      1      0      0     
     [,199] [,200]
[1,] 0      1

[1] 5031

In [29]:
gen300.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen300_1.txt")

In [30]:
a <- KnapsackSimpleExact(gen300.1)
matrix(a$solution, ncol = gen300.1$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    1    0    0    1    1    0    0    0    0     0     0     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     1     1     1     1     1     1     0     0     1     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     1     0     0     1     0     1     0     0     1     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     0     1     0     0     1     0     1     0     0     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     1     1     1     0     1     1     1     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     0     1     0     1     1     1     1     1     1     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     1     0     1     1     0     1     0     0     1     0     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 1     1     0     1     1     0     0     1     1     0     0     1    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 0     0      ⋯      0      1      1      1      1      1      0     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      1      0      1      1      0      0      0      1      0     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 1      0      0      0      0      0      1      1      0      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      0      1      1      1      1      0      0      0      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 1      1      0      1      0      1      1      1      0      0     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      1      0      1      0      0      0      1      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      1      1      1      1      1      1      1      0      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 1      1      0      1      0      1      0      1      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      0      0      1      0      1      1      0      0      1     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      0      1      0      1      0      0      0      1      1     
     [,199] [,200] [,201]
[1,] 0      1      0

[1] 11219

In [31]:
gen300.2 <- ReadSimpleKnapsack("./data/knapsack/simple/gen300_2.txt")

In [32]:
a <- KnapsackSimpleExact(gen300.2)
matrix(a$solution, ncol = gen300.2$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    1    0    1    0    1    1    0     0     1     1     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     1     1     0     0     1     0     1     0     1    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     1     1     1     0     1     1     1     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     1     1     1     1     1     1     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 1     0     0     0     1     1     1     0     1     1     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     0     1     1     1     1     0     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     1     0     1     0     1     1     0     0     1     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     1     1     0     1     1     1     1     1     0     1    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     1      ⋯      1      0      1      1      1      0      1     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 1      1      0      0      0      0      1      0      1      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 1      1      1      1      1      0      1      0      1      0     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      0      0      1      0      1      1      0      1      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      0      0      1      1      1      0      1      1      1     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      0      0      1      1      1      0      0      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      0      1      0      1      0      1      1      1      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 0      0      1      1      0      0      1      1      0      1     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      0      0      1      0      1      0      0      0      0     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      1      1      0      1      0      0      1      1      0     
     [,199] [,200] [,201]
[1,] 1      0      1

[1] 11399

In [33]:
gen300.3 <- ReadSimpleKnapsack("./data/knapsack/simple/gen300_3.txt")

In [34]:
a <- KnapsackSimpleExact(gen300.3)
matrix(a$solution, ncol = gen300.3$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    1    0    1    0    0    1    1    1     0     1     1     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     1     1     1     0     1     1     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     0     1     0     1     0     0     0     1     0     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     1     0     0     1     0     1     1     1     1     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     1     1     1     1     1     0     0     1     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     1     0     1     1     0     0     0     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     1     0     0     0     1     1     1     0     1     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     1     0     1     0     1     1     0     1     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     1      ⋯      0      0      0      1      1      1      1     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 1      1      1      1      1      1      1      1      0      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      0      0      0      1      0      0      0      1      0     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 0      1      0      0      0      1      1      1      1      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 0      1      1      0      1      1      1      1      1      1     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 0      0      1      1      1      0      1      1      0      1     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 0      1      0      1      1      0      0      0      1      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 1      1      1      1      0      0      1      0      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 1      1      1      1      1      0      1      1      0      0     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 1      1      0      1      1      1      0      1      0      0     
     [,199] [,200] [,201]
[1,] 0      1      1

[1] 11298

In [35]:
gen300.4 <- ReadSimpleKnapsack("./data/knapsack/simple/gen300_4.txt")

In [36]:
a <- KnapsackSimpleExact(gen300.4)
matrix(a$solution, ncol = gen300.4$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    1    1    0    0    0    0    0    1     1     0     1     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     1     1     1     0     1     0     0     1     1     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     1     0     1     1     0     0     0     0     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     0     0     1     1     0     0     0     0     0     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 1     1     0     1     0     0     0     1     0     1     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     1     0     1     1     1     1     0     1     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     0     0     0     0     0     1     1     0     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 1     1     0     0     1     0     0     1     0     0     0     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     0      ⋯      1      0      0      0      1      1      1     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 0      1      1      0      0      1      0      1      1      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 1      0      1      0      1      0      0      0      1      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      0      1      0      1      1      1      0      0      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 1      1      1      1      1      1      1      1      0      1     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      1      1      0      1      0      1      1      1     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 1      0      0      1      1      1      1      0      1      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 1      0      0      1      1      0      1      1      1      1     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 0      1      0      1      1      0      1      0      1      1     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      0      0      1      0      1      1      1      0      1     
     [,199] [,200] [,201]
[1,] 0      0      1

[1] 10985

In [37]:
gen300.5 <- ReadSimpleKnapsack("./data/knapsack/simple/gen300_5.txt")

In [38]:
a <- KnapsackSimpleExact(gen300.5)
matrix(a$solution, ncol = gen300.5$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    0    1    1    0    0    0    1    1    1     1     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     1     1     0     1     1     0     0     0     1     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     1     0     0     1     0     1     0     1     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     0     1     1     1     0     0     1     0     0     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 1     0     1     1     0     1     1     1     1     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     1     1     1     0     1     1     1     1     1     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     1     0     1     1     1     1     0     1     1     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     1     1     1     0     0     0     1     0     0    
     [,99] [,100] [,101] [,102] [,103] [,104] [,105] [,106] [,107] [,108]
[1,] 1     1      ⋯      0      1      1      0      1      1      1     
     [,109] [,110] [,111] [,112] [,113] [,114] [,115] [,116] [,117] [,118]
[1,] 1      0      0      0      1      0      1      1      0      1     
     [,119] [,120] [,121] [,122] [,123] [,124] [,125] [,126] [,127] [,128]
[1,] 0      0      1      0      1      1      0      0      0      1     
     [,129] [,130] [,131] [,132] [,133] [,134] [,135] [,136] [,137] [,138]
[1,] 1      1      1      0      0      0      1      0      0      0     
     [,139] [,140] [,141] [,142] [,143] [,144] [,145] [,146] [,147] [,148]
[1,] 1      0      0      0      1      1      0      1      1      0     
     [,149] [,150] [,151] [,152] [,153] [,154] [,155] [,156] [,157] [,158]
[1,] 1      1      0      1      1      1      1      0      1      0     
     [,159] [,160] [,161] [,162] [,163] [,164] [,165] [,166] [,167] [,168]
[1,] 0      0      1      0      0      0      1      1      1      1     
     [,169] [,170] [,171] [,172] [,173] [,174] [,175] [,176] [,177] [,178]
[1,] 1      1      0      0      0      1      1      1      0      0     
     [,179] [,180] [,181] [,182] [,183] [,184] [,185] [,186] [,187] [,188]
[1,] 0      0      1      1      1      1      1      1      0      0     
     [,189] [,190] [,191] [,192] [,193] [,194] [,195] [,196] [,197] [,198]
[1,] 0      1      0      1      0      0      1      0      1      0     
     [,199] [,200] [,201]
[1,] 0      1      1

[1] 11122

### Mochila Múltiple

#### Descripción:
TODO

#### Modelo:
TODO

In [39]:
KnapsackMultipleExact <- function(p, m, ...) {
    conditions <- matrix(rep(0,(m + p$n) * p$n * m), 
                         nrow = m + p$n, ncol = p$n * m, byrow = TRUE)
    
    
    
    for(i in 1:m) {
        conditions[i, (i - 1) * p$n + 1:p$n] <- p$weight
    }
    for(i in (m + 1):(p$n + m)) {
        conditions[i, seq(i-m, p$n*m, by = p$n)] <- 1
    }

    return(Solve("max", rep(p$value, m), conditions, c(rep(p$capacity, m), rep(1, p$n)),
                 all.bin = TRUE, ...))
}
gen10.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen10_1.txt")
m <- 3
a <- KnapsackMultipleExact(gen10.1, m)
matrix(a$solution, ncol = gen10.1$n, nrow = m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    1    1    1    0     0     0     0     1    
[2,] 0    1    1    0    0    0    0    0    0    0     1     0     1     0    
[3,] 1    0    0    1    1    1    0    0    0    1     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     0     0     0     0     1     1     1     0    
[2,] 0     0     0     0     1     0     1     0     0     0     0     1    
[3,] 1     1     1     1     0     1     0     1     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     0     1     0     0     0     0     1     0     0     0    
[2,] 1     1     0     0     0     0     0     1     0     1     0     0    
[3,] 0     0     1     0     1     1     1     0     0     0     1     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     1     0     0     0     0     0     0    
[2,] 1     1     0     0     0     0     1     0     0     1     1     1    
[3,] 0     0     1     1     1     0     0     1     0     0     0     0

[1] 2286

#### Heurísticas:
TODO

In [40]:
KnapsackMultipleGreedy <- function(object, capacity) {
    
}

### Ejemplos

### Mochila Multidimensional

#### Descripción:
TODO

In [41]:
ReadMultidimensionalKnapsack <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.double()
    close(con)
    list(n        = raw[1],
         m        = raw[2],
         objval   = raw[3],
         value    = raw[4:(raw[1]+ 3)],
         weight   = matrix(raw[(4 + raw[1]):(3 + raw[1] * (1 + raw[2]))], 
                           ncol = raw[1], byrow = TRUE),
         capacity = raw[(4 + raw[1] * (1 + raw[2]) ):length(raw)]
    ) %>%
    return()
}

#### Modelo:
TODO

In [42]:
KnapsackMultidimensionalExact <- function(p, ...) {    
    return(Solve("max", p$value, p$weight, p$capacity, all.bin = TRUE,...))
}

#### Heurísticas:
TODO

In [43]:
KnapsackMultidimensionalGreedy <- function(object, capacity) {
    
}

### Ejemplos

In [44]:
mknap1.2 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_2.dat")

In [45]:
a <- KnapsackMultidimensionalExact(mknap1.2)
matrix(a$solution, ncol = mknap1.2$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0    1    0    1    1    0    0    1    0    1

[1] 8706.1

In [46]:
mknap1.3 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_3.dat")

In [47]:
a <- KnapsackMultidimensionalExact(mknap1.3)
matrix(a$solution, ncol = mknap1.3$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    1    0    1    0    1    1    0    1    1     0     0     0     1    
     [,15]
[1,] 1

[1] 4015

In [48]:
mknap1.4 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_4.dat")

In [49]:
a <- KnapsackMultidimensionalExact(mknap1.4)
matrix(a$solution, ncol = mknap1.4$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    0    0    0    0    0    0    0    0    1     0     0     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,] 1     1     1     1     1     1

[1] 6120

In [50]:
mknap1.6 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_6.dat")

In [51]:
a <- KnapsackMultidimensionalExact(mknap1.6)
matrix(a$solution, ncol = mknap1.6$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    1    0    1    0    1    0    1    1    0     1     0     1     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     1     1     1     1     1     0     0     1     0     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     1     1     0     1     1     0     1     1     1     1     1    
     [,39]
[1,] 1

[1] 10618

In [52]:
mknap1.7 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_7.dat")

In [53]:
a <- KnapsackMultidimensionalExact(mknap1.7)
matrix(a$solution, ncol = mknap1.7$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    1    0    1    0    1    1    0     1     1     1     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     1     1     0     1     1     0     0     1     0     1     1    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     1     1     0     1     1     0     1     1     1     1     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 1     1     1     1     1     1     0     0     1     1     1     1

[1] 16537

In [54]:
mknapcb1.1 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknapcb1_1.dat")

In [55]:
a <- KnapsackMultidimensionalExact(mknapcb1.1)
matrix(a$solution, ncol = mknapcb1.1$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    1    0    1    0    0    1    0    1    0     1     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     1     0     0     0     0     1     0     1    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     0     1     1     0     1     0     0     0     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     1     0     0     0     0     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     0     0     0     1     0     0     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     0     1     0     0     1     0     1     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     1     0     1     0     0     0     0     0     1     1    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     0     0     1     1     0     0     1     0     0    
     [,99] [,100]
[1,] 1     0

[1] 24381

In [56]:
mknapcb1.2 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknapcb1_2.dat")

In [57]:
a <- KnapsackMultidimensionalExact(mknapcb1.2)
matrix(a$solution, ncol = mknapcb1.2$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    1    0    0    0    0    0    0     1     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     1     0     1     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     1     1     0     0     0     0     0     1     0     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     1     1     0     0     1     0     0     1     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     1     0     0     1     1     1     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     1     0     0     0     0     0     0     0     0     1    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     0     0     0     1     0     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     1     0     1     1     0     1     0     1     0     0    
     [,99] [,100]
[1,] 0     1

[1] 24274

In [58]:
mknapcb1.3 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknapcb1_3.dat")

In [59]:
a <- KnapsackMultidimensionalExact(mknapcb1.3)
matrix(a$solution, ncol = mknapcb1.3$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    1    0    0    0    0    0     0     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     1     1     0     1     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 1     0     1     0     0     0     1     0     1     0     0     1    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     1     0     1     0     0     0     1     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     1     0     0     0     1     0     0     0     1     1     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     0     1     0     0     0     0     0     0     0     1     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     1     1     0     0     0     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     0     0     0     1     1     0     0     1     0    
     [,99] [,100]
[1,] 0     1

[1] 23551

In [60]:
mknapcb1.4 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknapcb1_4.dat")

In [61]:
a <- KnapsackMultidimensionalExact(mknapcb1.4)
matrix(a$solution, ncol = mknapcb1.4$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    1    0    1    0    1    0    0    1    0     0     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     0     0     0     0     0     1     0     1     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     1     0     0     1     0     0     0     1     1     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     1     0     0     0     0     0     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     0     0     1     1     1     1     0     1     0     0     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 0     1     0     0     0     0     0     0     0     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 1     0     0     0     1     1     0     0     0     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 1     0     0     0     0     0     0     0     1     1     0     0    
     [,99] [,100]
[1,] 0     0

[1] 23534

In [62]:
mknapcb1.5 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknapcb1_5.dat")

In [63]:
a <- KnapsackMultidimensionalExact(mknapcb1.5)
matrix(a$solution, ncol = mknapcb1.5$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    1    0    0    1    0    0    0    1    0     0     0     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 0     0     0     1     0     0     0     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     1     0     0     0     0     0     1     0     0     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     1     0     0     0     1     0     1     0     0     1    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 1     0     0     0     1     1     1     0     0     0     1     1    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     0     1     1     1     0     0     0     1     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     0     0     1     0     1     0     0     0     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     1     0     0     0     0     1     0     0     1     1     0    
     [,99] [,100]
[1,] 1     1

[1] 23991