# Programación Entera: Heurísticas para el Problema de Asignación

## Descripción

[TODO]

## Autor
  
  * Sergio García Prado - [garciparedes.me](https://garciparedes.me)
  
## Fecha

  * Mayo de 2018


## Contenidos
  
  * [Problema de Asignación](#Problema-de-Asignación)
    * [Asignación Clásico](#Asignación-Clásico)
    * [Asignación Generalizado](#Asignación-Generalizado)

In [1]:
library(lpSolve)
library(magrittr)

In [2]:
options(repr.matrix.max.rows = 600, repr.matrix.max.cols = 200)

## Funciones de Apoyo

In [3]:
dataset.folder <- "./data"

In [4]:
ReadDataSet <- function() {
    
}

In [5]:
Solve <- function(direction = "max", f.obj, f.con, f.rhs, f.dir = rep("<=", nrow(f.con)), ...) {
    lp(direction, f.obj, f.con, f.dir, f.rhs, ...)
}

## Problema de Asignación

### Asignación Clásico

#### Descripción:
TODO

#### Modelo:
TODO

In [6]:
AssignmentExact <- function(cost, ...) {
    demand <- rep(1, dim(cost)[1])
    capacity <- rep(1, dim(cost)[2])
    m <- length(capacity)
    n <- length(demand) 
    sol <- list(solution = matrix(0, nrow = m, ncol = n), 
                objval = 0, slack = capacity)
    while (!all(demand == 0)) {
        ij <- which(cost == min(cost[sol$slack > 0, demand > 0]), arr.ind = TRUE)
        ij.slice <- which(sol$slack[ij[, 1]] > 0 & demand[ij[, 2]] > 0)[1]
        i <- ij[ij.slice, 1]
        j <- ij[ij.slice, 2]
        inc <- min(sol$slack[i], demand[j])    
        
        sol$solution[i, j] <- sol$solution[i, j] + inc
        sol$slack[i] <- sol$slack[i] - inc
        demand[j] <- demand[j] - inc
        sol$objval <- sol$objval + cost[i, j] * inc
    }
    return(sol)
}

#### Heurísticas:
TODO

In [7]:
AssignmentGreedy <- function(cost) {   
    demand <- rep(1, dim(cost)[1])
    capacity <- rep(1, dim(cost)[2]) 
    m <- length(capacity)
    n <- length(demand) 
    sol <- list(solution = matrix(0, nrow = m, ncol = n), 
                objval = 0, slack = capacity)
    while (!all(demand == 0)) {
        ij <- which(cost == min(cost[sol$slack > 0, demand > 0]), arr.ind = TRUE)
        ij.slice <- which(sol$slack[ij[, 1]] > 0 & demand[ij[, 2]] > 0)[1]
        i <- ij[ij.slice, 1]
        j <- ij[ij.slice, 2]
        inc <- min(sol$slack[i], demand[j])    
        
        sol$solution[i, j] <- sol$solution[i, j] + inc
        sol$slack[i] <- sol$slack[i] - inc
        demand[j] <- demand[j] - inc
        sol$objval <- sol$objval + cost[i, j] * inc
    }
    return(sol)
}

In [8]:
GreedyLocalSearchImprovement <- function(change.1, change.2, cost) {
    return((cost[change.1[, drop = FALSE]] + cost[change.2[, drop = FALSE]]) -
           (cost[change.1[1], change.2[2]] + cost[change.2[1], change.1[2]]))
}

In [9]:
GreedyLocalSearchBest <- function(cost, changes) {
    best = list(v = 0, i = 0, j = 0)
    for (i in 1:nrow(changes)) {
        for(j in 1:nrow(changes)) {
            v.temp <- GreedyLocalSearchImprovement(changes[i, ,drop = FALSE], 
                                                   changes[j, , drop = FALSE],
                                                   cost)
            if (best$v < v.temp) {
                best$v <- v.temp
                best$i <- i
                best$j <- j
            }
        }
    }
    return(best)
}

In [10]:
AssignmentGreedyLocalSearch <- function(cost) {    
    sol <- AssignmentGreedy(cost)
        
    changes <- which(sol$solution != 0, arr.ind = TRUE)
    best <- GreedyLocalSearchBest(cost, changes)
    while(best$v > 0) {

        sol$solution[changes[best$i, , drop = FALSE]] <- 0
        sol$solution[changes[best$j, , drop = FALSE]] <- 0
        
        temp <- changes[best$i, 2]
        changes[best$i, 2] <- changes[best$j, 2]
        changes[best$j, 2] <- temp
        
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 1
        sol$solution[changes[best$j, , drop = FALSE]] <- 1
        
        sol$objval <- sol$objval - best$v
        
        best <- GreedyLocalSearchBest(cost, changes)
    }
    return(sol)
}

### Ejemplos

In [11]:
(matriz.15x15.1 <- as.matrix(read.csv("./data/assignment/matriz_15x15_1.csv", header = FALSE)))

V1 V2 V3  V4 V5 V6  V7 V8 V9 V10 V11 V12 V13 V14 V15
 [1,] 58 66   6 77  7  19 44 22  9 90   86  11 61  11  26 
 [2,] 56 78  12 30 89  20 62 14 82 76   70 100 59  57  42 
 [3,] 93 80  90 77 71  96 55 25 46 57   16  30 91  55   0 
 [4,] 85 48  55 36 91  10 31 98 42 84   98  91 76  93  10 
 [5,] 62 85  32 56 21  56 78 48 49 66    0  39 39   6  53 
 [6,] 44 64  25 47 56  63 80 35 22 70  100  96 32  84  70 
 [7,] 50 23   8 90 23  51 98 94 33 84   95  41 77  33  30 
 [8,]  9 32 100 36  3  21 66 19 91 48   81  57 86  96  35 
 [9,] 59 62  12 98 93  38 59 93 18 21   59  87 76   9  82 
[10,] 37  1  13 29 85  18 29 20 54 94   30   1  0  67  51 
[11,] 79 67  50 23 67  26 98 26 22 33   81  83 66  59  14 
[12,]  5 39  98 54 32  80  6 11 63 20   87  95 82  73   7 
[13,] 80 45  10 71 95 100 26 66 14 95   62  16 13  68  32 
[14,] 29 44  82 49 87  47 63 66 91 10   52  14  2  44  89 
[15,] 79  3  16 11 13  97  6 18 93 22   28  77  3  37  53

In [12]:
a <- AssignmentExact(matriz.15x15.1)
matrix(a$solution, nrow = dim(matriz.15x15.1)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
 [2,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
 [3,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [4,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
 [5,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
 [6,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
 [7,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
 [8,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
 [9,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[10,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
[11,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
[12,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
[13,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
[14,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
[15,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
      [,14] [,15]
 [1,] 0     0    
 [2,] 0     0    
 [3,] 0     1    
 [4,] 0     0    
 [5,] 0     0    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 0     0    
 [9,] 1     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 0     0    
[14,] 0     0    
[15,] 0     0

V11 
218

In [13]:
AssignmentGreedy(matriz.15x15.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [6,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [7,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [8,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    1     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     1     0     0     0
[15,]    0    1    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     1
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     1     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
V11 
218 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [14]:
AssignmentGreedyLocalSearch(matriz.15x15.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     1     0     0     0
[15,]    0    1    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     1
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     1     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
V11 
144 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [15]:
(matriz.15x15.2 <- as.matrix(read.csv("./data/assignment/matriz_15x15_2.csv", header = FALSE)))

V1  V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15
 [1,]   6 51 28 33 12 43 24 72 15 93   12  0  83  28  43 
 [2,]  36 29 45 40 61 88  6 70 73 64   12 86  35  42  13 
 [3,]  77 40 77 49 54 71 85  8 99 16   96 61  74  16  66 
 [4,]  79 48 43 25 84 96 48 74 65 21   49 23   9  83   7 
 [5,] 100 23 36  2 44 28 66 15 80 45   70 47  89  18  33 
 [6,]   5 50 92 82 96 41 75 92 86 12   15 74  41  89  25 
 [7,]  62  5 81 41 84 23 69 87 37 24   29 31  55  80  81 
 [8,]  64 46 60 98 40 57 76 23 17 84   99  6  65  27  65 
 [9,]  84  0 28 16 81 85 24 21 88  5   76 47  22  23  33 
[10,]   3 74 78 80 97 10 86 30 16 74   88 35  96  56  99 
[11,]  76 32 31 82 33 23 70 40 83 75   26 40  42  30  87 
[12,]  52 74 93  6 14 48 92 96 71 57  100 42   7  25  43 
[13,]  37 29 55 40  3 39 18  4 37 49   23 40  30   4  32 
[14,]  36 13 40 10 14 73 13 60 65 55   10 94  46  85  84 
[15,]  12 23 96 10 67 43 11 79  7 83   44 17  52  32  14

In [16]:
a <- AssignmentExact(matriz.15x15.2)
matrix(a$solution, nrow = dim(matriz.15x15.2)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
 [2,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
 [3,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
 [4,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [5,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
 [6,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
 [7,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
 [8,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [9,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
[10,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
[11,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
[13,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
[15,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
      [,14] [,15]
 [1,] 0     0    
 [2,] 0     0    
 [3,] 0     0    
 [4,] 0     1    
 [5,] 0     0    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 1     0    
 [9,] 0     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 0     0    
[14,] 0     0    
[15,] 0     0

V2 
146

In [17]:
AssignmentGreedy(matriz.15x15.2)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [5,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [7,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[10,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[13,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     0     1     0     0
[15,]    0    0    0    0    0    0    0    0    1     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     1
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     1     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
 V2 
146 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [18]:
AssignmentGreedyLocalSearch(matriz.15x15.2)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [5,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [7,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[10,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[13,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     0     1     0     0
[15,]    0    0    0    0    0    0    0    0    1     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     1
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     1     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
 V2 
146 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [19]:
(matriz.15x15.3 <- as.matrix(read.csv("./data/assignment/matriz_15x15_3.csv", header = FALSE)))

V1  V2 V3 V4 V5 V6 V7 V8  V9 V10 V11 V12 V13 V14 V15
 [1,]  60 40 71 35 28 40 51  79 61 43  76  12  43   0  96 
 [2,]  93  8 72  6 44 88 76  36 83 16  12   9  84  77  31 
 [3,]  28 24 61  5 49 12 18  74 96 82  85  63  48  80  45 
 [4,]  13 33 54 73 92 86 47  66  6 99  60   2  77  16  57 
 [5,]  15 48 83 80 23  8 66  75 41 64  12  49  36  28  15 
 [6,]  92 15 89 42 28 41 84 100  7 40  70  50  43  81  96 
 [7,]  43  6 25  3 23 65 70  89 25 69  76  24  30  21  29 
 [8,]  24 40 56 65 98 86 45  74 33  5  78  29  17  46  85 
 [9,]  27 84  0  5 83 22 96  86 25 55  99  85  40  16  21 
[10,]  33  6 99 30 47 23 74  65 64 32  80  23  39  23  52 
[11,]  74 88 81 14 60 41 48  31 70 37  74  30  87  33  76 
[12,] 100 62 42 26 10 65  7  92 87 42   7  13  40  82  55 
[13,]  97 12 84 97 74 43 40  46 81 71  75  18  35  36  32 
[14,]  12 37 13 72 11 96 40   4 16 52  93  96  78  18  94 
[15,]  58 88 29 57 23  4 39  73 58 80  19  14  17  25  44

In [20]:
a <- AssignmentExact(matriz.15x15.3)
matrix(a$solution, nrow = dim(matriz.15x15.3)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [2,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
 [3,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
 [4,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
 [5,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
 [6,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
 [7,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
 [8,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
 [9,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
[10,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
[11,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
[12,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[14,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
[15,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
      [,14] [,15]
 [1,] 1     0    
 [2,] 0     0    
 [3,] 0     0    
 [4,] 0     0    
 [5,] 0     0    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 0     0    
 [9,] 0     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 0     1    
[14,] 0     0    
[15,] 0     0

V3 
205

In [21]:
AssignmentGreedy(matriz.15x15.3)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     1
 [4,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [5,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [9,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[10,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    1    0     0     0     0     0
[15,]    0    0    0    0    0    1    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     1     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     1
[14,]     0     0
[15,]     0     0

$objval
 V3 
205 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [22]:
AssignmentGreedyLocalSearch(matriz.15x15.3)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [3,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [5,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [9,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[10,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    1    0     0     0     0     0
[15,]    0    0    0    0    0    0    0    0    0     0     0     0     1
      [,14] [,15]
 [1,]     1     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     1
[14,]     0     0
[15,]     0     0

$objval
 V3 
156 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### Asignación Generalizado

In [23]:
ReadGeneralizedAssignment <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.integer()
    close(con)
    list(m        = raw[1],
         n        = raw[2], 
         cost     = matrix(raw[3:(2 + raw[1] * raw[2])], 
                           nrow = raw[1], ncol = raw[2], byrow = TRUE),
         resource = matrix(raw[(3 + raw[1] * raw[2]):(2 + 2 * raw[1] * raw[2])], 
                           nrow = raw[1], ncol = raw[2], byrow = TRUE),
         capacity = raw[(3 + 2 * raw[1] * raw[2]):length(raw)]
        
    ) %>%
    return()
}

#### Descripción:
TODO

#### Modelo:
TODO

In [24]:
GeneralizedAssignmentExact <- function(problem.statement, direction = "max", ...) {    
    
    m <- problem.statement$m
    n <- problem.statement$n
    cost <- problem.statement$cost
    resource <- problem.statement$resource
    capacity <- problem.statement$capacity
    demand <- rep(1, n)
    
    
    conditions <- matrix(0, nrow = n + m, ncol = n * m)
    for (i in 1:m) {
        conditions[i, seq(n) + (i - 1) * n] <- resource[i, ]
    }
    for (i in (m + 1):(n + m)) {
        conditions[i, seq(i - m, m * n, by = n)] <- 1
    }
    res <- c(rep("<=", m), rep("=", n))
    return(Solve(direction, t(cost), conditions, c(capacity, demand), res, all.bin = TRUE, ...))
}

#### Heurísticas:
TODO

In [25]:
GeneralizedAssignmentGreedy <- function(p) {    
    sol <- list(solution = matrix(0, nrow = p$m, ncol = p$n), 
                objval = 0, slack = p$capacity)
    while(!all(colSums(sol$solution) == 1)) {
        max.resource <- max(sol$slack - p$resource[,colSums(sol$solution) == 0])
        
        ij <- which(sol$slack - p$resource == max.resource, arr.ind = TRUE)
        ij <- ij[colSums(sol$solution[, ij[,2], drop = FALSE]) == 0, , drop = FALSE]
        ij <- ij[which.max(p$cost[ij]), ,drop = FALSE]
        
        sol$solution[ij[1], ij[2]] <- 1
        sol$slack[ij[1]] <- sol$slack[ij[1]] - p$resource[ij[1], ij[2]]
        sol$objval <- sol$objval + p$cost[ij[1], ij[2]]
    }
    return(sol)
}

In [26]:
AssignmentGreedyLocalSearchImprovement <- function(change.1, change.2, cost) {
    return( - (cost[change.1[, drop = FALSE]] + cost[change.2[, drop = FALSE]]) +
              (cost[change.1[1], change.2[2]] + cost[change.2[1], change.1[2]]))
}

In [27]:
AssignmentGreedyLocalSearchBest <- function(p, changes, slack) {
    best = list(v = 0, i = 0, j = 0)
    for (i in 1:nrow(changes)) {
        for(j in 1:nrow(changes)) {
            if ((slack[changes[i, , drop = FALSE][1]] + p$resource[changes[i, , drop = FALSE]] - 
                     p$resource[changes[i, 1], changes[j, 2]] > 0) & 
                (slack[changes[j, , drop = FALSE][1]] + p$resource[changes[j, , drop = FALSE]] - 
                     p$resource[changes[j, 1], changes[i, 2]] > 0)) { 
                    
                    v.temp <- AssignmentGreedyLocalSearchImprovement(changes[i, ,drop = FALSE], 
                                                                     changes[j, , drop = FALSE],
                                                                     p$cost)
                    if (best$v < v.temp) {
                        best$v <- v.temp
                        best$i <- i
                        best$j <- j
                    }
                }
        }
    }
    return(best)
}

In [28]:
GeneralizedAssignmentGreedyLocalSearch <- function(p) {
    sol <- GeneralizedAssignmentGreedy(p)
    
    changes <- which(sol$solution != 0, arr.ind = TRUE)
    slack <- rowSums(sol$solution * p$resource)
    best <- AssignmentGreedyLocalSearchBest(p, changes, sol$slack)
    while(best$v > 0) {
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 0
        sol$solution[changes[best$j, , drop = FALSE]] <- 0
        sol$slack[changes[best$i][1]] <- sol$slack[changes[best$i][1]] + p$resource[changes[best$i, , drop = FALSE]]
        sol$slack[changes[best$j][1]] <- sol$slack[changes[best$j][1]] + p$resource[changes[best$j, , drop = FALSE]]
        
        temp <- changes[best$i, 2]
        changes[best$i, 2] <- changes[best$j, 2]
        changes[best$j, 2] <- temp
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 1
        sol$solution[changes[best$j, , drop = FALSE]] <- 1
        
        sol$slack[changes[best$i][1]] <- sol$slack[changes[best$i][1]] - p$resource[changes[best$i, , drop = FALSE]]
        sol$slack[changes[best$j][1]] <- sol$slack[changes[best$j][1]] - p$resource[changes[best$j, , drop = FALSE]]
        sol$objval <- sol$objval + best$v
        best <- AssignmentGreedyLocalSearchBest(p, changes, sol$slack)
    }
    return(sol)
}

### Ejemplos

In [29]:
gap2.1 <- ReadGeneralizedAssignment("./data/assignment/gap2_1.txt")

In [30]:
a <- GeneralizedAssignmentExact(gap2.1)
matrix(a$solution, nrow = gap2.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    1    0    0    1    0    0    1    0     0     0     0     0    
[2,] 0    0    0    0    0    0    1    0    0    1     0     0     0     0    
[3,] 1    0    0    0    1    0    0    0    0    0     0     0     1     0    
[4,] 0    0    0    1    0    0    0    1    0    0     0     0     0     0    
[5,] 0    1    0    0    0    0    0    0    0    0     1     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,] 0     0     0     0     0     1    
[2,] 0     1     0     0     1     0    
[3,] 0     0     1     0     0     0    
[4,] 1     0     0     1     0     0    
[5,] 0     0     0     0     0     0

[1] 434

In [31]:
GeneralizedAssignmentGreedy(gap2.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    1    0    0    0    0    0    1     0     0     1     0     0
[2,]    0    0    0    0    0    0    1    0    0     0     0     0     0     0
[3,]    0    0    0    0    0    1    0    1    0     0     0     0     1     0
[4,]    1    0    0    1    0    0    0    0    0     1     0     0     0     0
[5,]    0    1    0    0    1    0    0    0    0     0     1     0     0     1
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]     0     0     0     1     0     0
[2,]     1     1     0     0     1     0
[3,]     0     0     0     0     0     1
[4,]     0     0     1     0     0     0
[5,]     0     0     0     0     0     0

$objval
[1] 377

$slack
[1] 14 14 13 13 10

In [32]:
GeneralizedAssignmentGreedyLocalSearch(gap2.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    1     0     1     1     0     0
[2,]    0    0    0    0    0    0    1    0    0     1     0     0     0     0
[3,]    1    0    0    0    0    1    0    0    0     0     0     0     1     0
[4,]    0    0    0    1    0    0    0    1    0     0     0     0     0     0
[5,]    0    1    1    0    1    0    0    0    0     0     0     0     0     1
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]     0     0     0     0     0     1
[2,]     0     1     0     0     1     0
[3,]     0     0     1     0     0     0
[4,]     1     0     0     1     0     0
[5,]     0     0     0     0     0     0

$objval
[1] 432

$slack
[1] 2 4 2 4 7

In [33]:
gap4.1 <- ReadGeneralizedAssignment("./data/assignment/gap4_1.txt")

In [34]:
a <- GeneralizedAssignmentExact(gap4.1)
matrix(a$solution, nrow = gap4.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    1    0    0    0     0     0     0     0    
[2,] 0    1    0    0    1    0    0    0    0    0     1     0     1     0    
[3,] 0    0    0    0    0    0    0    1    1    0     0     0     0     1    
[4,] 1    0    0    0    0    0    0    0    0    1     0     0     0     0    
[5,] 0    0    1    1    0    1    0    0    0    0     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     0     0     0     0     0     0     0     1    
[2,] 0     1     1     0     0     0     0     0     0     0     0     0    
[3,] 0     0     0     0     1     0     0     0     0     1     0     0    
[4,] 0     0     0     0     0     1     0     1     1     0     1     0    
[5,] 0     0     0     0     0     0     1     0     0     0     0     0    
     [,27] [,28] [,29] [,30]
[1,] 0     1     0     0    
[2,] 0     0     1     0    
[3,] 1     0     0     0    
[4,] 0     0     0     0    
[5,] 0     0     0     1

[1] 656

In [35]:
GeneralizedAssignmentGreedy(gap4.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    0    0    0    0    1     0     0     1     0     0
[2,]    0    0    0    0    1    0    1    0    0     0     1     0     1     0
[3,]    0    0    0    0    0    1    0    0    0     0     0     0     0     1
[4,]    0    0    0    1    0    0    0    0    0     1     0     0     0     0
[5,]    0    1    1    0    0    0    0    1    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     1     1     0     0     0
[3,]     0     0     0     0     1     0     1     0     0     0     0     1
[4,]     0     1     1     1     0     0     0     0     0     1     0     0
[5,]     1     0     0     0     0     1     0     0     0     0     1     0
     [,27] [,28] [,29] [,30]
[1,]     0     1     1     1
[2,]     0     0     0     0
[3,]     1     0     0     0
[4,]     0     0     0     0
[5,]     0     0     0     0

$objval
[1] 541

$slack
[1] 19 28 11 20 20

In [36]:
GeneralizedAssignmentGreedyLocalSearch(gap4.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    1    0    1     0     1     0     0     0
[2,]    0    1    0    0    1    0    0    0    0     0     0     1     1     0
[3,]    0    0    0    0    0    0    0    1    0     0     0     0     0     1
[4,]    1    0    0    0    0    0    0    0    0     1     0     0     0     0
[5,]    0    0    1    1    0    1    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     1     1     0     0     0     0     0     0     0     0     0
[3,]     0     0     0     0     1     0     0     0     0     1     0     1
[4,]     0     0     0     1     0     0     0     1     1     0     1     0
[5,]     0     0     0     0     0     1     1     0     0     0     0     0
     [,27] [,28] [,29] [,30]
[1,]     0     1     1     0
[2,]     0     0     0     0
[3,]     1     0     0     0
[4,]     0     0     0     0
[5,]     0     0     0     1

$objval
[1] 650

$slack
[1] 10  1  5  3  4

In [37]:
gap6.1 <- ReadGeneralizedAssignment("./data/assignment/gap6_1.txt")

In [38]:
a <- GeneralizedAssignmentExact(gap6.1)
matrix(a$solution, nrow = gap6.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    0    0    0    0     0     0     0     0    
[2,] 0    1    0    0    0    0    1    0    0    0     0     0     0     0    
[3,] 1    0    0    0    0    0    0    1    0    0     0     0     0     0    
[4,] 0    0    0    0    1    0    0    0    0    0     0     0     0     0    
[5,] 0    0    0    0    0    0    0    0    0    0     0     0     0     1    
[6,] 0    0    1    0    0    0    0    0    0    0     0     0     1     0    
[7,] 0    0    0    1    0    1    0    0    0    0     0     0     0     0    
[8,] 0    0    0    0    0    0    0    0    1    1     1     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     1     0     1     0     0     0     0     0     1     0    
[2,] 0     0     0     0     0     1     0     0     1     0     0     0    
[3,] 0     0     0     0     0     0     0     0     0     0     0     0    
[4,] 0     0     0     0     0     0     0     0     0     0     0     0    
[5,] 0     0     0     0     0     0     0     1     0     0     0     0    
[6,] 0     0     0     0     0     0     0     0     0     1     0     1    
[7,] 0     1     0     1     0     0     0     0     0     0     0     0    
[8,] 0     0     0     0     0     0     1     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,] 0     0     0     0     0     0    
[2,] 0     0     0     0     0     0    
[3,] 0     0     0     0     0     0    
[4,] 0     0     0     0     1     1    
[5,] 0     0     1     1     0     0    
[6,] 1     0     0     0     0     0    
[7,] 0     1     0     0     0     0    
[8,] 0     0     0     0     0     0

[1] 761

In [39]:
GeneralizedAssignmentGreedy(gap6.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    0    0    0    0    1    1    0    0     0     0     0     0     0
[2,]    0    0    0    0    1    0    0    0    0     0     0     0     0     0
[3,]    0    1    0    0    0    0    0    0    0     0     0     0     0     0
[4,]    0    0    0    0    0    0    0    0    0     0     1     1     0     0
[5,]    0    0    0    0    0    0    0    0    1     0     0     0     0     1
[6,]    0    0    0    0    0    0    0    0    0     0     0     0     1     0
[7,]    0    0    0    1    0    0    0    0    0     0     0     0     0     0
[8,]    0    0    1    0    0    0    0    1    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     1     1     0     1     1     0     0     0
[3,]     0     0     1     1     0     0     0     0     0     0     0     0
[4,]     0     1     0     0     0     0     0     0     0     0     0     0
[5,]     1     0     0     0     0     0     0     0     0     0     0     1
[6,]     0     0     0     0     0     0     0     0     0     0     1     0
[7,]     0     0     0     0     0     0     0     0     0     1     0     0
[8,]     0     0     0     0     0     0     1     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]     0     0     0     0     0     0
[2,]     0     0     0     0     0     0
[3,]     0     0     0     0     1     0
[4,]     0     0     0     0     0     1
[5,]     0     0     0     0     0     0
[6,]     1     1     0     1     0     0
[7,]     0     0     1     0     0     0
[8,]     0     0     0     0     0     0

$objval
[1] 664

$slack
[1] 26  9 14 25 24 14 21 20

In [40]:
GeneralizedAssignmentGreedyLocalSearch(gap6.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    0    0    1     0     0     1     0     0
[2,]    0    0    0    0    0    0    1    0    0     1     0     0     0     0
[3,]    0    1    0    0    0    0    0    0    0     0     0     0     0     0
[4,]    1    0    0    0    0    0    0    0    0     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     1
[6,]    0    0    1    0    0    0    0    0    0     0     0     0     1     0
[7,]    0    0    0    1    0    0    0    0    0     0     0     0     0     0
[8,]    0    0    0    0    1    0    0    1    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     1     1     0     0     1     0     0     0
[3,]     0     0     1     0     0     0     0     0     0     0     0     0
[4,]     0     1     0     0     0     0     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     1     0     0     1     0
[6,]     0     0     0     0     0     0     0     0     0     1     0     1
[7,]     1     0     0     1     0     0     0     0     0     0     0     0
[8,]     0     0     0     0     0     0     1     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]     0     0     0     0     0     0
[2,]     0     0     0     0     0     0
[3,]     1     0     0     1     0     0
[4,]     0     0     0     0     1     1
[5,]     0     0     1     0     0     0
[6,]     0     1     0     0     0     0
[7,]     0     0     0     0     0     0
[8,]     0     0     0     0     0     0

$objval
[1] 746

$slack
[1] 5 3 1 4 7 6 6 2

In [41]:
gap8.1 <- ReadGeneralizedAssignment("./data/assignment/gap8_1.txt")

In [42]:
# a <- GeneralizedAssignmentExact(gap8.1)
# matrix(a$solution, nrow = gap8.1$m, byrow = TRUE)
# a$objval

In [43]:
GeneralizedAssignmentGreedy(gap8.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    1    0    0    0    0    0     1     0     0     0     0
[2,]    1    0    1    0    0    0    0    0    0     0     0     0     1     0
[3,]    0    0    0    0    0    0    1    0    0     0     0     0     0     0
[4,]    0    0    0    0    0    0    0    1    1     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     1     0     0
[6,]    0    0    0    0    1    1    0    0    0     0     0     0     0     0
[7,]    0    0    0    0    0    0    0    0    0     0     0     0     0     1
[8,]    0    0    0    0    0    0    0    0    0     0     1     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     1     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     1     0     0     0     1     0     1     0     0     0     0
[4,]     0     0     0     1     0     0     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     1     0     0     0     0     0
[6,]     0     0     0     0     1     0     0     0     1     0     0     1
[7,]     0     0     0     0     0     0     0     0     0     1     1     0
[8,]     1     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     0     1     0     0     0
[3,]     0     0     0     0     1     0     1     0     0     0     0     0
[4,]     0     0     0     0     0     0     0     0     0     0     0     1
[5,]     1     0     0     1     0     0     0     1     0     0     0     0
[6,]     0     0     0     0     0     0     0     0     0     1     0     0
[7,]     0     0     1     0     0     1     0     0     0     0     1     0
[8,]     0     1     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]
[1,]     1     0     0     0     0     1     0     0     0     0
[2,]     0     0     0     0     0     0     1     1     0     0
[3,]     0     0     0     0     0     0     0     0     0     0
[4,]     0     1     0     1     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     0     1     1
[6,]     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     0     0     0     0     0     0
[8,]     0     0     1     0     1     0     0     0     0     0

$objval
[1] 990

$slack
[1]  8 16 14 17  6 12  8 16

In [44]:
GeneralizedAssignmentGreedyLocalSearch(gap8.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    1    0    0    0    0    0    0    0     1     0     0     0     0
[2,]    0    0    1    0    0    0    0    0    0     0     1     0     1     0
[3,]    0    0    0    0    0    0    1    0    0     0     0     0     0     0
[4,]    0    0    0    0    0    0    0    0    1     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[6,]    1    0    0    0    1    1    0    1    0     0     0     0     0     0
[7,]    0    0    0    0    0    0    0    0    0     0     0     0     0     1
[8,]    0    0    0    1    0    0    0    0    0     0     0     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     0     1     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     1     0     0     0     0     0     0     0     0     0     0
[4,]     0     0     1     1     0     0     0     0     0     0     0     0
[5,]     0     0     0     0     0     1     1     0     0     0     0     1
[6,]     0     0     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     0     0     0     0     1     1     1     0
[8,]     0     0     0     0     0     0     0     1     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     1     0     0     1     0     0     1
[3,]     1     0     0     0     1     0     1     0     0     0     0     0
[4,]     0     0     0     0     0     0     0     1     0     0     0     0
[5,]     0     0     0     1     0     0     0     0     0     0     0     0
[6,]     0     0     0     0     0     0     0     0     0     1     0     0
[7,]     0     0     1     0     0     0     0     0     0     0     1     0
[8,]     0     1     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]
[1,]     0     0     0     0     0     1     0     1     0     0
[2,]     0     0     0     0     0     0     0     0     0     0
[3,]     0     0     1     0     0     0     0     0     0     0
[4,]     0     1     0     1     0     0     0     0     0     0
[5,]     1     0     0     0     0     0     0     0     1     1
[6,]     0     0     0     0     0     0     1     0     0     0
[7,]     0     0     0     0     0     0     0     0     0     0
[8,]     0     0     0     0     1     0     0     0     0     0

$objval
[1] 1100

$slack
[1] 1 2 1 2 4 2 4 1

In [45]:
gap12.1 <- ReadGeneralizedAssignment("./data/assignment/gap12_1.txt")

In [46]:
# a <- GeneralizedAssignmentExact(gap12.1)
# matrix(a$solution, nrow = gap12.1$m, byrow = TRUE)
# a$objval

In [47]:
GeneralizedAssignmentGreedy(gap12.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    1     0     0     0     1
 [2,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [3,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    1    0    0    1    0     0     1     0     0
 [5,]    0    1    0    0    0    0    1    0    0     1     0     0     0
 [6,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [7,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     1     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
 [1,]     0     0     0     0     1     0     1     0     0     0     0     0
 [2,]     0     0     0     0     0     0     0     1     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     1     1     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     1
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     0     0     0     0     0     0     0     0     0     0
 [7,]     0     1     0     0     0     0     0     0     1     0     0     0
 [8,]     0     0     0     0     0     1     0     0     0     0     0     0
 [9,]     0     0     0     1     0     0     0     0     0     0     0     0
[10,]     1     0     1     0     0     0     0     0     0     0     0     0
      [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
 [1,]     0     0     0     0     0     0     1     0     0     0     0     0
 [2,]     0     0     0     0     0     0     0     0     1     0     1     0
 [3,]     0     0     0     0     0     1     0     0     0     0     0     0
 [4,]     0     1     0     0     1     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     0     0     0     0     0     0     0     0     0     1
 [7,]     0     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0     0     0     1     0     0     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     0     0     0     1     0     0
[10,]     1     0     1     0     0     0     0     1     0     0     0     0
      [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
 [1,]     0     1     0     0     0     0     0     1     0     0     0     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     1     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     0     1     0     1     0     0     0     0     0     0
 [7,]     0     0     0     0     0     0     0     0     1     0     1     1
 [8,]     0     0     0     0     1     0     0     0     0     0     0     0
 [9,]     1     0     0     0     0     0     1     0     0     0     0     0
[10,]     0     0     1     0     0     0     0     0     0     0     0     0
      [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60]
 [1,]     0     0     0     0     0     0     0     0     0     0     0
 [2,]     0     1     0     1     0     0     0     0     0     1     0
 [3,]     1     0     0     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     1
 [5,]     0     0     1     0     0     0     1     0     0     0     0
 [6,]     0     0     0     0     0     1     0     0     0     0     0
 [7,]     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0    

In [48]:
GeneralizedAssignmentGreedyLocalSearch(gap12.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    1    0    0    0    0    1    0    0    1     0     0     1     0
 [2,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [3,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [5,]    0    1    0    0    0    0    0    0    0     1     1     0     0
 [6,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [7,]    0    0    0    0    0    0    0    1    0     0     0     0     1
 [8,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[10,]    0    0    0    0    0    0    1    0    0     0     0     0     0
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
 [1,]     0     0     0     0     0     0     0     1     0     0     0     0
 [2,]     1     0     1     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     1     0     0
 [4,]     0     0     0     0     0     0     0     0     1     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     1
 [6,]     0     0     0     0     0     0     0     0     0     0     0     0
 [7,]     0     1     0     0     1     0     0     0     0     0     0     0
 [8,]     0     0     0     0     0     1     0     0     0     0     0     0
 [9,]     0     0     0     1     0     0     0     0     0     0     0     0
[10,]     0     0     0     0     0     0     1     0     0     0     1     0
      [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
 [1,]     0     0     0     0     0     0     1     0     0     0     0     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     1     0     0     0     0     0     0
 [4,]     0     1     0     0     1     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     1     0
 [6,]     0     0     0     0     0     0     0     1     0     1     0     1
 [7,]     0     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0     0     0     1     0     0     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     0     0     1     0     0     0
[10,]     1     0     1     0     0     0     0     0     0     0     0     0
      [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
 [1,]     0     0     0     0     0     0     0     0     0     0     1     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     1     0     0     0     0     0     0     0     1     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     0     0     0     1     0     0     1     0     0     0
 [7,]     0     0     0     0     1     0     0     0     0     0     0     1
 [8,]     1     0     0     1     0     0     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     1     1     0     0     0     0
[10,]     0     0     1     0     0     0     0     0     0     0     0     0
      [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60]
 [1,]     0     0     0     0     0     0     0     0     0     0     0
 [2,]     0     1     0     1     0     0     0     0     1     1     0
 [3,]     1     0     0     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     1     0     1     1     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     0     0     0     0     0     0     0     0     0
 [7,]     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0    