# Programación Entera: Heurísticas

## Descripción

[TODO]

## Autor
  
  * Sergio García Prado - [garciparedes.me](https://garciparedes.me)
  
## Fecha

  * Mayo de 2018


## Contenidos
  
  * [Problema de Transporte](#Problema-de-Transporte)
  * [Problema de Asignación](#Problema-de-Asignación)
    * [Asignación Clásico](#Asignación-Clásico)
    * [Asignación Generalizado](#Asignación-Generalizado)
  * [Problema de la Mochila](#Problema-de-la-Mochila)
    * [Mochila Simple](#Mochila-Simple)
    * [Mochila Múltiple](#Mochila-Múltiple)
    * [Mochila Multidimensional](#Mochila-Multidimensional)

In [1]:
library(lpSolve)
library(magrittr)

In [2]:
options(repr.matrix.max.rows = 600, repr.matrix.max.cols = 200)

## Funciones de Apoyo

In [3]:
dataset.folder <- "./data"

In [4]:
ReadDataSet <- function() {
    
}

In [5]:
Solve <- function(direction = "max", f.obj, f.con, f.rhs, f.dir = rep("<=", nrow(f.con)), ...) {
    lp(direction, f.obj, f.con, f.dir, f.rhs, ...)
}

## Problema de Transporte

#### Descripción:
TODO

#### Modelo:
TODO

In [6]:
TransportationExact <- function(demand, capacity, cost, direction = "min", ...) {
    m <- length(capacity)
    n <- length(demand)    
    
    conditions <- matrix(0, nrow = n + m, ncol = n * m)
    for (i in 1:m) {
        conditions[i, seq(n) + (i - 1) * n] <- 1
    }
    for (i in (m+1):(n+m)) {
        conditions[i, seq(i - m, m * n, by = n)] <- 1
    }
    res <- c(rep("<=", m), rep(">=", n))
    return(Solve(direction, cost, conditions, c(capacity, demand), res, ...))
}

#### Heurísticas:
TODO

In [7]:
TransportationGreedy <- function(demand, capacity, cost) {
    m <- length(capacity)
    n <- length(demand) 
    sol <- list(solution = matrix(0, nrow = m, ncol = n), 
                objval = 0, slack = capacity)
    while (!all(demand == 0)) {
        ij <- which(cost == min(cost[sol$slack > 0, demand > 0]), arr.ind = TRUE)
        ij.slice <- which(sol$slack[ij[, 1]] > 0 & demand[ij[, 2]] > 0)[1]
        i <- ij[ij.slice, 1]
        j <- ij[ij.slice, 2]
        inc <- min(sol$slack[i], demand[j])    
        
        sol$solution[i, j] <- sol$solution[i, j] + inc
        sol$slack[i] <- sol$slack[i] - inc
        demand[j] <- demand[j] - inc
        sol$objval <- sol$objval + cost[i, j] * inc
    }
    return(sol)
}

### Ejemplos

In [8]:
transportation.problem.1 <- list(
    demand = c(45, 20, 30, 30),
    capacity = c(35, 60, 48),
    cost = matrix(c(8, 6, 10, 9,
                    9, 12,13, 7,
                    14,9, 16, 5), nrow = 3, byrow = TRUE)
)

In [9]:
a <- TransportationExact(transportation.problem.1$demand,
                    transportation.problem.1$capacity,
                    transportation.problem.1$cost)

matrix(a$solution, 
       nrow = 3, byrow =TRUE)
print(a$objval)

[,1] [,2] [,3] [,4]
[1,] 35    0    0    0  
[2,] 10   20   12    0  
[3,]  0    0   18   30

[1] 976


In [10]:
TransportationGreedy(transportation.problem.1$demand,
                    transportation.problem.1$capacity,
                    transportation.problem.1$cost)

$solution
     [,1] [,2] [,3] [,4]
[1,]   15   20    0    0
[2,]   30    0   30    0
[3,]    0    0    0   30

$objval
[1] 1050

$slack
[1]  0  0 18

## Problema de Asignación

### Asignación Clásico

#### Descripción:
TODO

#### Modelo:
TODO

In [11]:
AssignmentExact <- function(cost, ...) {
    return(TransportationExact(rep(1, dim(cost)[1]), rep(1, dim(cost)[2]), cost, ...))
}

#### Heurísticas:
TODO

In [12]:
AssignmentGreedy <- function(cost) {    
    return(TransportationGreedy(rep(1, dim(cost)[1]), rep(1, dim(cost)[2]), cost))
}

In [13]:
GreedyLocalSearchImprovement <- function(change.1, change.2, cost) {
    return((cost[change.1[, drop = FALSE]] + cost[change.2[, drop = FALSE]]) -
           (cost[change.1[1], change.2[2]] + cost[change.2[1], change.1[2]]))
}

In [14]:
GreedyLocalSearchBest <- function(cost, changes) {
    best = list(v = 0, i = 0, j = 0)
    for (i in 1:nrow(changes)) {
        for(j in 1:nrow(changes)) {
            v.temp <- GreedyLocalSearchImprovement(changes[i, ,drop = FALSE], 
                                                   changes[j, , drop = FALSE],
                                                   cost)
            if (best$v < v.temp) {
                best$v <- v.temp
                best$i <- i
                best$j <- j
            }
        }
    }
    return(best)
}

In [15]:
AssignmentGreedyLocalSearch <- function(cost) {    
    sol <- AssignmentGreedy(cost)
        
    changes <- which(sol$solution != 0, arr.ind = TRUE)
    best <- GreedyLocalSearchBest(cost, changes)
    while(best$v > 0) {

        sol$solution[changes[best$i, , drop = FALSE]] <- 0
        sol$solution[changes[best$j, , drop = FALSE]] <- 0
        
        temp <- changes[best$i, 2]
        changes[best$i, 2] <- changes[best$j, 2]
        changes[best$j, 2] <- temp
        
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 1
        sol$solution[changes[best$j, , drop = FALSE]] <- 1
        
        sol$objval <- sol$objval - best$v
        
        best <- GreedyLocalSearchBest(cost, changes)
    }
    return(sol)
}

### Ejemplos

In [16]:
(matriz.15x15.1 <- as.matrix(read.csv("./data/assignment/matriz_15x15_1.csv", header = FALSE)))

V1 V2 V3  V4 V5 V6  V7 V8 V9 V10 V11 V12 V13 V14 V15
 [1,] 58 66   6 77  7  19 44 22  9 90   86  11 61  11  26 
 [2,] 56 78  12 30 89  20 62 14 82 76   70 100 59  57  42 
 [3,] 93 80  90 77 71  96 55 25 46 57   16  30 91  55   0 
 [4,] 85 48  55 36 91  10 31 98 42 84   98  91 76  93  10 
 [5,] 62 85  32 56 21  56 78 48 49 66    0  39 39   6  53 
 [6,] 44 64  25 47 56  63 80 35 22 70  100  96 32  84  70 
 [7,] 50 23   8 90 23  51 98 94 33 84   95  41 77  33  30 
 [8,]  9 32 100 36  3  21 66 19 91 48   81  57 86  96  35 
 [9,] 59 62  12 98 93  38 59 93 18 21   59  87 76   9  82 
[10,] 37  1  13 29 85  18 29 20 54 94   30   1  0  67  51 
[11,] 79 67  50 23 67  26 98 26 22 33   81  83 66  59  14 
[12,]  5 39  98 54 32  80  6 11 63 20   87  95 82  73   7 
[13,] 80 45  10 71 95 100 26 66 14 95   62  16 13  68  32 
[14,] 29 44  82 49 87  47 63 66 91 10   52  14  2  44  89 
[15,] 79  3  16 11 13  97  6 18 93 22   28  77  3  37  53

In [17]:
a <- AssignmentExact(matriz.15x15.1)
matrix(a$solution, nrow = dim(matriz.15x15.1)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
 [2,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
 [3,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [4,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
 [5,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
 [6,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
 [7,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
 [8,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
 [9,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[10,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
[11,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
[12,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
[14,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
[15,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
      [,14] [,15]
 [1,] 0     0    
 [2,] 0     0    
 [3,] 0     1    
 [4,] 0     0    
 [5,] 0     0    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 0     0    
 [9,] 1     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 0     0    
[14,] 0     0    
[15,] 0     0

[1] 135

In [18]:
AssignmentGreedy(matriz.15x15.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [6,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [7,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [8,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    1     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     1     0     0     0
[15,]    0    1    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     1
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     1     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
V11 
218 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [19]:
AssignmentGreedyLocalSearch(matriz.15x15.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    1    0    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     1     0     0     0
[15,]    0    1    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     1
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     1     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
V11 
144 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [20]:
(matriz.15x15.2 <- as.matrix(read.csv("./data/assignment/matriz_15x15_2.csv", header = FALSE)))

V1  V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15
 [1,]   6 51 28 33 12 43 24 72 15 93   12  0  83  28  43 
 [2,]  36 29 45 40 61 88  6 70 73 64   12 86  35  42  13 
 [3,]  77 40 77 49 54 71 85  8 99 16   96 61  74  16  66 
 [4,]  79 48 43 25 84 96 48 74 65 21   49 23   9  83   7 
 [5,] 100 23 36  2 44 28 66 15 80 45   70 47  89  18  33 
 [6,]   5 50 92 82 96 41 75 92 86 12   15 74  41  89  25 
 [7,]  62  5 81 41 84 23 69 87 37 24   29 31  55  80  81 
 [8,]  64 46 60 98 40 57 76 23 17 84   99  6  65  27  65 
 [9,]  84  0 28 16 81 85 24 21 88  5   76 47  22  23  33 
[10,]   3 74 78 80 97 10 86 30 16 74   88 35  96  56  99 
[11,]  76 32 31 82 33 23 70 40 83 75   26 40  42  30  87 
[12,]  52 74 93  6 14 48 92 96 71 57  100 42   7  25  43 
[13,]  37 29 55 40  3 39 18  4 37 49   23 40  30   4  32 
[14,]  36 13 40 10 14 73 13 60 65 55   10 94  46  85  84 
[15,]  12 23 96 10 67 43 11 79  7 83   44 17  52  32  14

In [21]:
a <- AssignmentExact(matriz.15x15.2)
matrix(a$solution, nrow = dim(matriz.15x15.2)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
 [2,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
 [3,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
 [4,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [5,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
 [6,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
 [7,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
 [8,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
 [9,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
[10,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
[11,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
[13,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
[15,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
      [,14] [,15]
 [1,] 0     0    
 [2,] 0     0    
 [3,] 0     0    
 [4,] 0     1    
 [5,] 0     0    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 0     0    
 [9,] 0     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 1     0    
[14,] 0     0    
[15,] 0     0

[1] 125

In [22]:
AssignmentGreedy(matriz.15x15.2)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [5,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [7,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[10,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[13,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     0     1     0     0
[15,]    0    0    0    0    0    0    0    0    1     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     1
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     1     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
 V2 
146 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [23]:
AssignmentGreedyLocalSearch(matriz.15x15.2)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [2,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [3,]    0    0    0    0    0    0    0    1    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [5,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [7,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[10,]    1    0    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    0    0    0     0     0     0     1
[13,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    0    0     0     1     0     0
[15,]    0    0    0    0    0    0    0    0    1     0     0     0     0
      [,14] [,15]
 [1,]     0     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     1
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     1     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     0
[14,]     0     0
[15,]     0     0

$objval
 V2 
146 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [24]:
(matriz.15x15.3 <- as.matrix(read.csv("./data/assignment/matriz_15x15_3.csv", header = FALSE)))

V1  V2 V3 V4 V5 V6 V7 V8  V9 V10 V11 V12 V13 V14 V15
 [1,]  60 40 71 35 28 40 51  79 61 43  76  12  43   0  96 
 [2,]  93  8 72  6 44 88 76  36 83 16  12   9  84  77  31 
 [3,]  28 24 61  5 49 12 18  74 96 82  85  63  48  80  45 
 [4,]  13 33 54 73 92 86 47  66  6 99  60   2  77  16  57 
 [5,]  15 48 83 80 23  8 66  75 41 64  12  49  36  28  15 
 [6,]  92 15 89 42 28 41 84 100  7 40  70  50  43  81  96 
 [7,]  43  6 25  3 23 65 70  89 25 69  76  24  30  21  29 
 [8,]  24 40 56 65 98 86 45  74 33  5  78  29  17  46  85 
 [9,]  27 84  0  5 83 22 96  86 25 55  99  85  40  16  21 
[10,]  33  6 99 30 47 23 74  65 64 32  80  23  39  23  52 
[11,]  74 88 81 14 60 41 48  31 70 37  74  30  87  33  76 
[12,] 100 62 42 26 10 65  7  92 87 42   7  13  40  82  55 
[13,]  97 12 84 97 74 43 40  46 81 71  75  18  35  36  32 
[14,]  12 37 13 72 11 96 40   4 16 52  93  96  78  18  94 
[15,]  58 88 29 57 23  4 39  73 58 80  19  14  17  25  44

In [25]:
a <- AssignmentExact(matriz.15x15.3)
matrix(a$solution, nrow = dim(matriz.15x15.3)[1])
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [2,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
 [3,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
 [4,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
 [5,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [6,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
 [7,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
 [8,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
 [9,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
[10,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
[11,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
[12,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
[14,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
[15,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
      [,14] [,15]
 [1,] 1     0    
 [2,] 0     0    
 [3,] 0     0    
 [4,] 0     0    
 [5,] 0     1    
 [6,] 0     0    
 [7,] 0     0    
 [8,] 0     0    
 [9,] 0     0    
[10,] 0     0    
[11,] 0     0    
[12,] 0     0    
[13,] 0     0    
[14,] 0     0    
[15,] 0     0

[1] 153

In [26]:
AssignmentGreedy(matriz.15x15.3)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [3,]    0    0    0    0    0    0    0    0    0     0     0     0     1
 [4,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [5,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    0    1    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [9,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[10,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    0    0    1    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    1    0     0     0     0     0
[15,]    0    0    0    0    0    1    0    0    0     0     0     0     0
      [,14] [,15]
 [1,]     1     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     1
[14,]     0     0
[15,]     0     0

$objval
 V3 
205 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [27]:
AssignmentGreedyLocalSearch(matriz.15x15.3)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [2,]    0    0    0    0    0    0    0    0    0     0     1     0     0
 [3,]    0    0    0    0    0    1    0    0    0     0     0     0     0
 [4,]    0    0    0    0    0    0    0    0    0     0     0     1     0
 [5,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    0    0    0    0    1     0     0     0     0
 [7,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [9,]    0    0    1    0    0    0    0    0    0     0     0     0     0
[10,]    0    1    0    0    0    0    0    0    0     0     0     0     0
[11,]    0    0    0    1    0    0    0    0    0     0     0     0     0
[12,]    0    0    0    0    0    0    1    0    0     0     0     0     0
[13,]    0    0    0    0    0    0    0    0    0     0     0     0     0
[14,]    0    0    0    0    0    0    0    1    0     0     0     0     0
[15,]    0    0    0    0    0    0    0    0    0     0     0     0     1
      [,14] [,15]
 [1,]     1     0
 [2,]     0     0
 [3,]     0     0
 [4,]     0     0
 [5,]     0     0
 [6,]     0     0
 [7,]     0     0
 [8,]     0     0
 [9,]     0     0
[10,]     0     0
[11,]     0     0
[12,]     0     0
[13,]     0     1
[14,]     0     0
[15,]     0     0

$objval
 V3 
156 

$slack
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### Asignación Generalizado

In [28]:
ReadGeneralizedAssignment <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.integer()
    close(con)
    list(m        = raw[1],
         n        = raw[2], 
         cost     = matrix(raw[3:(2 + raw[1] * raw[2])], 
                           nrow = raw[1], ncol = raw[2], byrow = TRUE),
         resource = matrix(raw[(3 + raw[1] * raw[2]):(2 + 2 * raw[1] * raw[2])], 
                           nrow = raw[1], ncol = raw[2], byrow = TRUE),
         capacity = raw[(3 + 2 * raw[1] * raw[2]):length(raw)]
        
    ) %>%
    return()
}

#### Descripción:
TODO

#### Modelo:
TODO

In [29]:
GeneralizedAssignmentExact <- function(problem.statement, direction = "max", ...) {    
    
    m <- problem.statement$m
    n <- problem.statement$n
    cost <- problem.statement$cost
    resource <- problem.statement$resource
    capacity <- problem.statement$capacity
    demand <- rep(1, n)
    
    
    conditions <- matrix(0, nrow = n + m, ncol = n * m)
    for (i in 1:m) {
        conditions[i, seq(n) + (i - 1) * n] <- resource[i, ]
    }
    for (i in (m + 1):(n + m)) {
        conditions[i, seq(i - m, m * n, by = n)] <- 1
    }
    res <- c(rep("<=", m), rep("=", n))
    return(Solve(direction, t(cost), conditions, c(capacity, demand), res, all.bin = TRUE, ...))
}

#### Heurísticas:
TODO

In [30]:
GeneralizedAssignmentGreedy <- function(p) {    
    sol <- list(solution = matrix(0, nrow = p$m, ncol = p$n), 
                objval = 0, slack = p$capacity)
    while(!all(colSums(sol$solution) == 1)) {
        max.resource <- max(p$capacity - p$resource[,colSums(sol$solution) == 0])
        
        ij <- which(p$capacity - p$resource == max.resource, arr.ind = TRUE)
        ij <- ij[colSums(sol$solution[, ij[,2], drop = FALSE]) == 0, , drop = FALSE]
        ij <- ij[which.max(p$cost[ij]), ,drop = FALSE]
        
        sol$solution[ij[1], ij[2]] <- 1
        sol$slack[ij[1]] <- sol$slack[ij[1]] - p$resource[ij[1], ij[2]]
        sol$objval <- sol$objval + p$cost[ij[1], ij[2]]
    }
    return(sol)
}

In [31]:
AssignmentGreedyLocalSearchImprovement <- function(change.1, change.2, cost) {
    return( - (cost[change.1[, drop = FALSE]] + cost[change.2[, drop = FALSE]]) +
              (cost[change.1[1], change.2[2]] + cost[change.2[1], change.1[2]]))
}

In [32]:
AssignmentGreedyLocalSearchBest <- function(p, changes, slack) {
    best = list(v = 0, i = 0, j = 0)
    for (i in 1:nrow(changes)) {
        for(j in 1:nrow(changes)) {
            if ((slack[changes[i, , drop = FALSE][1]] + p$resource[changes[i, , drop = FALSE]] - 
                     p$resource[changes[i, 1], changes[j, 2]] > 0) & 
                (slack[changes[j, , drop = FALSE][1]] + p$resource[changes[j, , drop = FALSE]] - 
                     p$resource[changes[j, 1], changes[i, 2]] > 0)) { 
                    
                    v.temp <- AssignmentGreedyLocalSearchImprovement(changes[i, ,drop = FALSE], 
                                                                     changes[j, , drop = FALSE],
                                                                     p$cost)
                    if (best$v < v.temp) {
                        best$v <- v.temp
                        best$i <- i
                        best$j <- j
                    }
                }
        }
    }
    return(best)
}

In [33]:
GeneralizedAssignmentGreedyLocalSearch <- function(p) {
    sol <- GeneralizedAssignmentGreedy(p)
    
    changes <- which(sol$solution != 0, arr.ind = TRUE)
    slack <- rowSums(sol$solution * p$resource)
    best <- AssignmentGreedyLocalSearchBest(p, changes, sol$slack)
    while(best$v > 0) {
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 0
        sol$solution[changes[best$j, , drop = FALSE]] <- 0
        sol$slack[changes[best$i][1]] <- sol$slack[changes[best$i][1]] + p$resource[changes[best$i, , drop = FALSE]]
        sol$slack[changes[best$j][1]] <- sol$slack[changes[best$j][1]] + p$resource[changes[best$j, , drop = FALSE]]
        
        temp <- changes[best$i, 2]
        changes[best$i, 2] <- changes[best$j, 2]
        changes[best$j, 2] <- temp
        
        sol$solution[changes[best$i, , drop = FALSE]] <- 1
        sol$solution[changes[best$j, , drop = FALSE]] <- 1
        
        sol$slack[changes[best$i][1]] <- sol$slack[changes[best$i][1]] - p$resource[changes[best$i, , drop = FALSE]]
        sol$slack[changes[best$j][1]] <- sol$slack[changes[best$j][1]] - p$resource[changes[best$j, , drop = FALSE]]
        sol$objval <- sol$objval + best$v
        best <- AssignmentGreedyLocalSearchBest(p, changes, sol$slack)
    }
    return(sol)
}

### Ejemplos

In [34]:
(gap2.1 <- ReadGeneralizedAssignment("./data/assignment/gap2_1.txt"))

$m
[1] 5

$n
[1] 20

$cost
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   15   12   16   15   20   18   11   14   23    14    18    13    11    15
[2,]   22   14   10   15   12   21   24   16   17    22    11    15    18    15
[3,]   25   11   22   10   22   17   22   12   21    21    16    14    23    21
[4,]   23   13   14   25   21   18   23   19   17    18    20    20    22    24
[5,]   15   25   22   14   17   21   16   21   20    12    15    18    17    21
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]    17    18    20    11    20    24
[2,]    18    23    22    23    21    13
[3,]    14    17    25    18    15    15
[4,]    23    13    17    22    20    21
[5,]    20    20    13    14    23    14

$resource
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   11   11    5   25   10   17   16   20    5    20    14    10    15     6
[2,]   17   17   12   23   16   25   13   16   19    16    24    17    24     6
[3,]   13   13   20   17    8    7   16    9   23    18    21    24    11    15
[4,]    6   10   18   16   12   25   17    7   10     6    20    20     9    20
[5,]    7   14   18   24    7   24   18   19   18    23    15    16    14     9
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]    11    14    13     8    15    11
[2,]     6    16    25    21     5    18
[3,]    12    24    19    23    13    12
[4,]    11    21     6     9    20    23
[5,]    16    25    15    20    23    17

$capacity
[1] 42 54 52 47 55

In [35]:
a <- GeneralizedAssignmentExact(gap2.1)
matrix(a$solution, nrow = gap2.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    1    0    0    1    0    0    1    0     0     0     0     0    
[2,] 0    0    0    0    0    0    1    0    0    1     0     0     0     0    
[3,] 1    0    0    0    1    0    0    0    0    0     0     0     1     0    
[4,] 0    0    0    1    0    0    0    1    0    0     0     0     0     0    
[5,] 0    1    0    0    0    0    0    0    0    0     1     1     0     1    
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,] 0     0     0     0     0     1    
[2,] 0     1     0     0     1     0    
[3,] 0     0     1     0     0     0    
[4,] 1     0     0     1     0     0    
[5,] 0     0     0     0     0     0

[1] 434

In [36]:
GeneralizedAssignmentGreedy(gap2.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    1     0     0     0     0     0
[2,]    0    0    1    0    0    0    1    0    0     0     0     0     0     1
[3,]    0    0    0    1    0    1    0    1    0     0     0     0     1     0
[4,]    0    0    0    0    0    0    0    0    0     1     0     0     0     0
[5,]    1    1    0    0    1    0    0    0    0     0     1     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]     0     0     0     0     0     0
[2,]     1     1     0     0     1     0
[3,]     0     0     0     0     0     1
[4,]     0     0     1     1     0     0
[5,]     0     0     0     0     0     0

$objval
[1] 358

$slack
[1] 37 -4 -4 26 -4

In [37]:
GeneralizedAssignmentGreedyLocalSearch(gap2.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    1     0     0     0     0     0
[2,]    0    0    1    0    0    0    1    0    0     0     0     0     0     1
[3,]    0    0    0    1    0    1    0    1    0     0     0     0     1     0
[4,]    0    0    0    0    0    0    0    0    0     1     0     0     0     0
[5,]    1    1    0    0    1    0    0    0    0     0     1     1     0     0
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,]     0     0     0     0     0     0
[2,]     1     1     0     0     1     0
[3,]     0     0     0     0     0     1
[4,]     0     0     1     1     0     0
[5,]     0     0     0     0     0     0

$objval
[1] 358

$slack
[1] 37 -4 -4 26 -4

In [38]:
(gap4.1 <- ReadGeneralizedAssignment("./data/assignment/gap4_1.txt"))

$m
[1] 5

$n
[1] 30

$cost
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   15   16   12   17   12   15   19   15   19    17    25    17    19    15
[2,]   12   20   11   13   22   15   14   22   21    10    24    22    23    14
[3,]   19   19   16   11   18   20   18   22   21    15    22    23    16    23
[4,]   23   12   13   12   24   23   11   20   14    20    19    14    19    22
[5,]   15   13   16   23   19   21   15   12   18    21    12    18    21    16
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    20    16    12    16    13    22    16    16    14    21    21    24
[2,]    14    22    22    17    14    19    21    11    20    21    14    23
[3,]    18    18    18    22    21    12    20    18    13    25    10    23
[4,]    24    13    10    16    12    23    18    24    24    18    25    10
[5,]    17    14    13    14    19    18    21    12    14    17    15    24
     [,27] [,28] [,29] [,30]
[1,]    13    25    21    22
[2,]    10    17    24    22
[3,]    21    24    22    18
[4,]    18    18    19    15
[5,]    21    13    11    24

$resource
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    7   13   21   19   10   23   14   16   13    16    17    11    23    20
[2,]   12   12   23   23    6   24   13   24   16    17     9    15     5    20
[3,]   11   17   17   21   12   13   16   17   15    11    16    20    23    18
[4,]   18   23   13    8   15   12   16   13    9     6    12    13    13    14
[5,]   22    7    7   13   12   15   13   12   23    16    21     9    15    16
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     9    24    24    19    18    21    18    18    18    17    24    19
[2,]    19    17    16    13     8    13    24     5     6    25    10    16
[3,]    14    24    23    21     6    20    13    10    20    15    20    10
[4,]    18     6     6     7    12    10    22    10     8     8     9    18
[5,]     6    18    11    16    22     6     9     7    15     9     6    16
     [,27] [,28] [,29] [,30]
[1,]     9     9     7    13
[2,]    23     8     6    13
[3,]     8    23    24    18
[4,]     5     7    21    22
[5,]    17    23     5    10

$capacity
[1] 79 72 79 61 64

In [39]:
a <- GeneralizedAssignmentExact(gap4.1)
matrix(a$solution, nrow = gap4.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    1    0    0    0     0     0     0     0    
[2,] 0    1    0    0    1    0    0    0    0    0     1     0     1     0    
[3,] 0    0    0    0    0    0    0    1    1    0     0     0     0     1    
[4,] 1    0    0    0    0    0    0    0    0    1     0     0     0     0    
[5,] 0    0    1    1    0    1    0    0    0    0     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     1     0     0     0     0     0     0     0     1    
[2,] 0     1     1     0     0     0     0     0     0     0     0     0    
[3,] 0     0     0     0     1     0     0     0     0     1     0     0    
[4,] 0     0     0     0     0     1     0     1     1     0     1     0    
[5,] 0     0     0     0     0     0     1     0     0     0     0     0    
     [,27] [,28] [,29] [,30]
[1,] 0     1     0     0    
[2,] 0     0     1     0    
[3,] 1     0     0     0    
[4,] 0     0     0     0    
[5,] 0     0     0     1

[1] 656

In [40]:
GeneralizedAssignmentGreedy(gap4.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    1    1    0    1    1    1     0     0     1     0     0
[2,]    0    0    0    0    0    0    0    0    0     0     1     0     1     0
[3,]    0    0    1    0    0    1    0    0    0     1     0     0     0     1
[4,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     0     0     0     0     0     0     0     0
[2,]     0     1     1     0     0     1     0     0     1     0     1     0
[3,]     0     0     0     0     1     0     1     1     0     1     0     1
[4,]     0     0     0     0     0     0     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30]
[1,]     0     1     1     1
[2,]     0     0     0     0
[3,]     1     0     0     0
[4,]     0     0     0     0
[5,]     0     0     0     0

$objval
[1] 580

$slack
[1] -81  -4 -42  61  64

In [41]:
GeneralizedAssignmentGreedyLocalSearch(gap4.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    1    1    0    1    1    0    1    1    1     0     0     1     0     0
[2,]    0    0    0    0    0    0    0    0    0     0     1     0     1     0
[3,]    0    0    1    0    0    1    0    0    0     1     0     0     0     1
[4,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     1     0     0     1     0     0     0     0     0     0     0     0
[2,]     0     1     1     0     0     1     0     0     1     0     1     0
[3,]     0     0     0     0     1     0     1     1     0     1     0     1
[4,]     0     0     0     0     0     0     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30]
[1,]     0     1     1     1
[2,]     0     0     0     0
[3,]     1     0     0     0
[4,]     0     0     0     0
[5,]     0     0     0     0

$objval
[1] 580

$slack
[1] -81  -4 -42  61  64

In [42]:
(gap6.1 <- ReadGeneralizedAssignment("./data/assignment/gap6_1.txt"))

$m
[1] 8

$n
[1] 32

$cost
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   21   22   17   16   17   24   17   15   25    18    18    21    19    23
[2,]   18   24   18   22   19   25   23   15   24    22    19    19    20    25
[3,]   24   20   20   15   21   15   21   22   19    16    16    19    21    21
[4,]   21   20   16   21   20   18   22   17   18    19    16    15    21    24
[5,]   20   19   20   25   17   22   17   18   20    23    20    16    17    24
[6,]   17   24   22   23   17   20   19   16   24    21    25    16    25    23
[7,]   15   22   23   24   17   23   16   16   18    19    15    15    23    18
[8,]   20   18   18   24   25   20   16   19   25    24    25    24    15    22
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    24    25    25    16    22    20    20    20    20    21    24    19
[2,]    23    25    20    16    22    24    23    17    24    18    18    22
[3,]    15    17    24    17    19    18    21    25    17    24    21    24
[4,]    23    19    20    20    16    16    21    17    17    20    22    21
[5,]    18    16    20    23    22    15    15    23    18    21    25    20
[6,]    22    23    15    15    15    20    20    21    23    24    21    25
[7,]    24    25    18    25    18    15    16    22    19    18    19    22
[8,]    21    23    15    24    17    15    24    16    25    19    19    22
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]    22    15    20    17    17    22
[2,]    15    20    17    19    15    22
[3,]    25    17    19    24    21    22
[4,]    16    16    15    17    24    24
[5,]    18    19    24    25    17    16
[6,]    23    22    25    24    21    17
[7,]    18    23    16    15    25    25
[8,]    17    16    15    20    20    18

$resource
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   12   24   13   15   19    7    6   25   15    19    12    24    24    25
[2,]   10   20   10   24   10   25   11   11   23    14     6    16     5    20
[3,]   24    6   16   19   18    9   20   23   19    23    15    10    25    25
[4,]   17   19   11   25   24   11   16    8   22    18     5     6    21    22
[5,]    8    8   19   24   25   20   18   22    9    21    19    18    22     5
[6,]   10   23   10   17   19    7   11   22   25    19    12    25     5    20
[7,]    6    6   20    5   21    7   13    7   11     7    19    16    15    22
[8,]   13   21    7    8   24   15    9    6   16     5     6    10    23    20
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    15    19    15    24     8    18     9    23    10     8    11    10
[2,]    15    11    11    19     5     7    25     9     5    24     6    13
[3,]    12    17    16     8    10     9     9    21    19    11    14    22
[4,]    19     6    14    14    13    12    21    20     8    12    25    11
[5,]     6     6    23    15    12    25    14    10    18    14    10     5
[6,]     9    17    11    24     7    13    23    19    25     7     6    13
[7,]    19    13    24    12     8    25    17    12    14     5    11     9
[8,]     8    24    13     9     7    23     6    21    25     9     6    17
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]    18    21    20    14    20    16
[2,]    13    25    19    18    22     7
[3,]    20    23    23     9     8    25
[4,]    13    20    22    22    15     8
[5,]    22     7    17    16    21    13
[6,]     9     5    15     7    21     7
[7,]    18     5    11    22    14    12
[8,]    21     6     8    17    18    25

$capacity
[1] 51 45 52 50 49 46 42 44

In [43]:
a <- GeneralizedAssignmentExact(gap6.1)
matrix(a$solution, nrow = gap6.1$m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    0    0    0    0     0     0     0     0    
[2,] 0    1    0    0    0    0    1    0    0    0     0     0     0     0    
[3,] 1    0    0    0    0    0    0    1    0    0     0     0     0     0    
[4,] 0    0    0    0    1    0    0    0    0    0     0     0     0     0    
[5,] 0    0    0    0    0    0    0    0    0    0     0     0     0     1    
[6,] 0    0    1    0    0    0    0    0    0    0     0     0     1     0    
[7,] 0    0    0    1    0    1    0    0    0    0     0     0     0     0    
[8,] 0    0    0    0    0    0    0    0    1    1     1     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     1     0     1     0     0     0     0     0     1     0    
[2,] 0     0     0     0     0     1     0     0     1     0     0     0    
[3,] 0     0     0     0     0     0     0     0     0     0     0     0    
[4,] 0     0     0     0     0     0     0     0     0     0     0     0    
[5,] 0     0     0     0     0     0     0     1     0     0     0     0    
[6,] 0     0     0     0     0     0     0     0     0     1     0     1    
[7,] 0     1     0     1     0     0     0     0     0     0     0     0    
[8,] 0     0     0     0     0     0     1     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,] 0     0     0     0     0     0    
[2,] 0     0     0     0     0     0    
[3,] 0     0     0     0     0     0    
[4,] 0     0     0     0     1     1    
[5,] 0     0     1     1     0     0    
[6,] 1     0     0     0     0     0    
[7,] 0     1     0     0     0     0    
[8,] 0     0     0     0     0     0

[1] 761

In [44]:
GeneralizedAssignmentGreedy(gap6.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    1    0    0     0     0     0     0     0
[2,]    0    0    0    0    1    0    0    0    0     0     0     0     0     0
[3,]    0    1    0    0    0    0    0    0    0     0     0     0     0     0
[4,]    0    0    1    0    0    0    0    1    0     0     1     1     0     0
[5,]    1    0    0    0    0    0    0    0    1     0     0     0     0     1
[6,]    0    0    0    0    0    0    0    0    0     0     0     0     1     0
[7,]    0    0    0    1    0    0    0    0    0     0     0     0     0     0
[8,]    0    0    0    0    0    0    0    0    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     1     0     1     0     0     0     0     1     1     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     0     0     1     0     1     1     0     0     0     0     0
[4,]     0     1     0     0     0     0     0     0     1     0     0     0
[5,]     1     0     0     0     0     0     0     1     0     0     0     1
[6,]     0     0     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     0     0     0     0     0     0     0     0
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]     0     0     0     0     0     0
[2,]     0     0     0     0     0     0
[3,]     0     0     0     1     1     0
[4,]     0     0     0     0     0     1
[5,]     0     1     0     0     0     0
[6,]     1     0     0     0     0     0
[7,]     0     0     0     0     0     0
[8,]     0     0     1     0     0     0

$objval
[1] 652

$slack
[1] -4 35  3 -2 -1 32 37 31

In [45]:
GeneralizedAssignmentGreedyLocalSearch(gap6.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    1    1    0    0     0     0     0     0     0
[2,]    0    0    0    1    0    0    0    0    0     0     0     0     0     0
[3,]    0    1    0    0    0    0    0    0    0     0     0     0     0     0
[4,]    0    0    1    0    0    0    0    1    0     0     1     1     0     0
[5,]    1    0    0    0    0    0    0    0    1     0     0     0     0     1
[6,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[7,]    0    0    0    0    0    0    0    0    0     0     0     0     1     0
[8,]    0    0    0    0    1    0    0    0    0     1     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     1     0     1     0     0     0     0     1     1     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     0     0     1     0     1     1     0     0     0     0     0
[4,]     0     1     0     0     0     0     0     0     1     0     0     0
[5,]     1     0     0     0     0     0     0     1     0     0     0     1
[6,]     0     0     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     0     0     0     0     0     0     0     0
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32]
[1,]     0     0     0     0     0     0
[2,]     0     0     0     0     0     0
[3,]     0     0     0     1     1     0
[4,]     0     0     0     0     0     1
[5,]     0     1     0     0     0     0
[6,]     1     0     1     0     0     0
[7,]     0     0     0     0     0     0
[8,]     0     0     0     0     0     0

$objval
[1] 664

$slack
[1] -4 21  3 -2 -1 22 27 15

In [46]:
(gap8.1 <- ReadGeneralizedAssignment("./data/assignment/gap8_1.txt"))

$m
[1] 8

$n
[1] 48

$cost
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   21   25   18   18   21   25   22   18   18    23    17    24    16    21
[2,]   19   16   22   23   24   21   18   18   17    17    25    21    24    17
[3,]   23   19   16   20   20   18   24   15   24    17    24    21    15    19
[4,]   16   16   21   22   20   22   22   19   25    16    18    19    22    19
[5,]   16   15   22   23   16   23   20   20   23    16    19    16    18    20
[6,]   24   19   21   21   25   24   20   25   21    24    18    21    21    15
[7,]   24   23   18   22   25   18   16   21   24    25    18    16    16    23
[8,]   15   21   23   24   17   23   23   20   18    17    16    25    16    22
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    24    20    23    24    23    24    19    24    21    20    25    24
[2,]    17    22    15    24    18    21    21    23    19    24    19    22
[3,]    22    20    20    24    20    16    17    19    18    18    17    24
[4,]    18    22    25    20    23    17    18    21    16    20    16    15
[5,]    18    22    16    15    22    24    24    21    22    16    19    22
[6,]    23    24    18    23    20    25    22    20    17    25    16    22
[7,]    25    15    16    19    18    20    19    18    24    18    22    16
[8,]    20    17    21    18    17    17    18    24    24    24    24    18
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]    22    23    18    25    20    17    17    20    17    17    23    19
[2,]    17    18    24    24    21    24    16    21    23    22    19    20
[3,]    23    15    16    22    25    24    22    16    25    20    16    20
[4,]    21    20    18    16    23    16    22    22    18    22    17    15
[5,]    17    20    20    21    15    15    21    16    16    15    15    16
[6,]    19    18    22    25    16    16    22    23    22    23    16    21
[7,]    25    25    22    18    16    17    15    25    24    23    23    21
[8,]    20    21    23    24    19    18    18    19    22    16    23    16
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]
[1,]    18    15    19    24    24    25    16    23    17    18
[2,]    24    20    19    21    24    25    22    15    19    16
[3,]    18    15    24    24    15    24    23    24    18    25
[4,]    15    18    15    20    15    21    19    23    17    25
[5,]    24    25    19    24    22    22    20    19    17    24
[6,]    17    21    20    16    15    23    24    24    18    22
[7,]    25    22    24    19    16    21    16    15    16    25
[8,]    17    22    18    21    24    25    25    22    18    19

$resource
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    7    6    8    6   13   16    9   14   15     5    10     6    10     7
[2,]   10    7    5   10   16   14   15   10   16    15    16    16     5    12
[3,]   16    8   13   16   16   11    5   14   10     5    12    13    12    15
[4,]   15    7    5    7   14   15   12    6    5     9    13    16    10     6
[5,]    8   10    9   14    7   10    7   12   10    13    16     5    14    15
[6,]   13    9   11   13    5    8   13    7   10     8    10    11     5    15
[7,]   16   15   14   10    8   14    8   11   11     8    11     8    16     8
[8,]   12   13    7   14    7   10    5    7    8     5     8     9    10    16
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]    11    10    13     7    11    11     9    15    10    11    10    14
[2,]    16     6    12    12    10     9    15    11    13     8    12    10
[3,]    16     5    16     5    15     6     7     9    13    13    11     9
[4,]    15     9    15     5    16     6    11    13    15     8    13     9
[5,]     7    12    16    13    11    10     5    10    15    10     8     5
[6,]    14     6     8    13     8     8     9    12     6    11    15     6
[7,]    12  

In [47]:
# a <- GeneralizedAssignmentExact(gap8.1)
# matrix(a$solution, nrow = gap8.1$m, byrow = TRUE)
# a$objval

In [48]:
GeneralizedAssignmentGreedy(gap8.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[2,]    1    1    1    0    0    0    0    0    0     0     0     0     1     0
[3,]    0    0    0    0    0    0    1    0    0     1     0     0     0     0
[4,]    0    0    0    1    0    0    0    1    1     0     0     0     0     1
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[6,]    0    0    0    0    1    1    0    0    0     0     0     0     0     0
[7,]    0    0    0    0    0    0    0    0    0     0     1     1     0     0
[8,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     1     0     0     1     0     0     0     0     0     0     0
[3,]     0     0     0     1     0     0     0     0     0     0     0     0
[4,]     0     0     0     0     0     1     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     0     0     0     0     0
[6,]     0     0     1     0     0     0     0     0     1     0     0     0
[7,]     1     0     0     0     0     0     1     1     0     1     1     1
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     1     1     0     1     0     0     0
[3,]     0     0     0     0     1     0     0     1     0     0     0     0
[4,]     1     0     0     0     0     0     0     0     0     0     0     1
[5,]     0     0     0     1     0     0     0     0     0     0     0     0
[6,]     0     1     0     0     0     0     0     0     0     1     0     0
[7,]     0     0     1     0     0     0     0     0     0     0     1     0
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]
[1,]     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     1     1     0     0     1     1     0     0
[3,]     1     0     0     0     0     0     0     0     0     1
[4,]     0     1     0     0     0     1     0     0     1     0
[5,]     0     0     0     0     0     0     0     0     0     0
[6,]     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     1     0     0     0     0     0
[8,]     0     0     0     0     0     0     0     0     0     0

$objval
[1] 963

$slack
[1]  48 -36   7 -20  42  11 -37  47

In [49]:
GeneralizedAssignmentGreedyLocalSearch(gap8.1)

$solution
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[2,]    1    1    1    0    0    0    0    0    0     0     0     0     1     0
[3,]    0    0    0    0    0    0    1    0    0     1     0     0     0     0
[4,]    0    0    0    1    0    0    0    1    1     0     0     0     0     1
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[6,]    0    0    0    0    1    1    0    0    0     0     0     0     0     0
[7,]    0    0    0    0    0    0    0    0    0     0     1     1     0     0
[8,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     1     0     0     1     0     0     0     0     0     0     0
[3,]     0     0     0     1     0     0     0     0     0     0     0     0
[4,]     0     0     0     0     0     1     0     0     0     0     0     0
[5,]     0     0     0     0     0     0     0     0     1     0     0     0
[6,]     0     0     1     0     0     0     0     0     0     0     0     0
[7,]     1     0     0     0     0     0     1     1     0     1     1     1
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     1     1     0     1     0     0     0
[3,]     0     0     0     1     1     0     0     0     0     0     0     0
[4,]     1     0     0     0     0     0     0     0     0     0     0     1
[5,]     0     0     0     0     0     0     0     0     0     0     0     0
[6,]     0     1     0     0     0     0     0     1     0     1     0     0
[7,]     0     0     1     0     0     0     0     0     0     0     1     0
[8,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]
[1,]     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     1     1     0     0     1     1     0     0
[3,]     1     0     0     0     0     0     0     0     0     1
[4,]     0     1     0     0     0     1     0     0     1     0
[5,]     0     0     0     0     0     0     0     0     0     0
[6,]     0     0     0     0     0     0     0     0     0     0
[7,]     0     0     0     0     1     0     0     0     0     0
[8,]     0     0     0     0     0     0     0     0     0     0

$objval
[1] 976

$slack
[1]  48 -36   4 -20  33   2 -37  47

In [50]:
(gap12.1 <- ReadGeneralizedAssignment("./data/assignment/gap12_1.txt"))

$m
[1] 10

$n
[1] 60

$cost
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]   25   18   15   16   18   25   19   18   25    23    19    25    19
 [2,]   21   21   15   23   23   22   20   22   21    24    20    19    23
 [3,]   21   17   24   17   24   15   22   24   20    18    21    23    19
 [4,]   21   20   22   15   23   24   25   22   18    16    23    24    20
 [5,]   24   23   22   19   18   16   23   18   22    24    25    16    23
 [6,]   16   21   19   22   16   16   17   23   25    16    18    22    15
 [7,]   23   23   19   18   19   19   21   24   22    16    17    25    24
 [8,]   24   16   15   25   16   15   20   20   22    18    21    19    21
 [9,]   18   18   18   19   18   24   22   19   25    15    16    23    17
[10,]   16   18   19   18   18   24   24   23   25    16    20    22    25
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
 [1,]    21    24    16    18    23    18    17    25    20    24    21    17
 [2,]    24    23    23    22    22    15    18    20    19    20    24    22
 [3,]    24    23    22    22    21    16    18    21    22    25    22    17
 [4,]    21    15    21    17    20    24    22    24    25    16    17    18
 [5,]    21    17    18    19    17    25    17    18    23    24    18    24
 [6,]    25    20    15    18    23    22    16    17    17    16    24    24
 [7,]    17    23    17    20    25    25    22    17    24    17    17    23
 [8,]    19    17    17    17    22    25    17    20    25    15    17    20
 [9,]    16    18    22    21    18    21    18    20    18    16    24    17
[10,]    16    20    18    19    24    24    25    22    23    23    24    18
      [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
 [1,]    19    24    25    17    19    19    25    20    17    21    20    20
 [2,]    20    20    20    20    17    20    24    18    19    22    17    21
 [3,]    25    22    22    24    22    25    20    16    19    23    20    18
 [4,]    20    25    18    24    24    24    22    19    20    15    20    17
 [5,]    23    23    15    19    18    24    19    19    24    24    24    15
 [6,]    16    17    23    19    23    15    17    24    19    24    24    24
 [7,]    23    16    17    19    19    23    24    17    25    18    19    18
 [8,]    16    23    20    23    22    23    15    21    24    21    23    19
 [9,]    22    24    18    22    18    24    23    23    25    20    23    18
[10,]    24    16    21    17    22    22    16    15    17    19    23    15
      [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
 [1,]    17    19    25    25    19    23    24    20    16    21    24    17
 [2,]    17    19    17    22    22    18    22    20    17    19    15    15
 [3,]    23    23    19    19    21    17    22    15    16    23    24    17
 [4,]    19    16    23    15    22    22    24    15    16    20    17    21
 [5,]    21    21    24    24    19    23    24    21    23    24    22    18
 [6,]    16    22    16    18    23    23    20    16    25    23    17    18
 [7,]    16    17    17    24    23    17    19    15    23    22    17    23
 [8,]    24    17    24    25    18    24    21    20    18    22    15    16
 [9,]    22    21    18    24    17    15    25    23    16    22    24    18
[10,]    19    22    22    23    23    16    20    22    24    20    20    23
      [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60]
 [1,]    15    17    19    15    21    25    16    21    20    24    22
 [2,]    19    23    22    24    23    17    21    25    23    20    19
 [3,]    22    23    18    24    16    20    25    19    17    22    21
 [4,]    24    24    24    24    25    19    24    25    16    22    19
 [5,]    19    24    15    17    17    25    17    24    16    19    21
 [6,]    23    24    19    22    19    19    18    21    21    22    17
 [7,]    21    15    19    18    22    23    16    16    22    16    

In [51]:
# a <- GeneralizedAssignmentExact(gap12.1)
# matrix(a$solution, nrow = gap12.1$m, byrow = TRUE)
# a$objval

In [52]:
GeneralizedAssignmentGreedy(gap12.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    1    0    0    1    0    0    1     0     0     0     1
 [2,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [3,]    0    0    0    1    0    0    1    0    0     0     1     0     0
 [4,]    0    1    0    0    0    0    0    1    0     1     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [7,]    1    0    0    0    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     1     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
 [1,]     0     0     1     0     1     0     1     1     0     0     0     1
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     0     1     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     1     1     0     0     0     0     0     0     0     1     0     0
 [7,]     0     0     0     0     0     0     0     0     1     0     0     0
 [8,]     0     0     0     0     0     1     0     0     0     0     0     0
 [9,]     0     0     0     1     0     0     0     0     0     0     0     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
 [1,]     0     0     1     0     0     1     1     1     0     1     0     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     1     0     1     1     0     0     0     0     0     0     1
 [7,]     1     0     0     0     0     0     0     0     1     0     0     0
 [8,]     0     0     0     0     0     0     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     0     0     0     0     1     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
 [1,]     0     1     0     0     0     0     0     1     0     0     1     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     1     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     1     1     0     1     0     0     1     0     0     0
 [7,]     0     0     0     0     1     0     0     0     0     0     0     1
 [8,]     0     0     0     0     0     0     0     0     0     0     0     0
 [9,]     1     0     0     0     0     0     1     0     0     0     0     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60]
 [1,]     0     0     0     1     0     0     1     0     0     0     0
 [2,]     0     1     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     1     0     0     0     0     0     0
 [4,]     0     0     0     0     0     0     0     1     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0
 [6,]     1     0     1     0     0     1     0     0     0     1     0
 [7,]     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0    

In [53]:
GeneralizedAssignmentGreedyLocalSearch(gap12.1)

$solution
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    1    0    0    1    0    0    1     0     0     0     1
 [2,]    0    0    0    0    0    0    0    0    0     1     0     0     0
 [3,]    0    0    0    1    0    0    0    1    0     0     1     0     0
 [4,]    0    0    0    0    0    0    1    0    0     0     0     0     0
 [5,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [6,]    0    0    0    0    1    0    0    0    0     0     0     0     0
 [7,]    1    1    0    0    0    0    0    0    0     0     0     0     0
 [8,]    0    0    0    0    0    0    0    0    0     0     0     0     0
 [9,]    0    0    0    0    0    0    0    0    0     0     0     1     0
[10,]    0    0    0    0    0    0    0    0    0     0     0     0     0
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
 [1,]     0     0     1     0     1     0     1     1     0     0     0     1
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     1     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     0     0     0     0     1     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     1     1     0     0     0     0     0     0     0     1     0     0
 [7,]     0     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0     0     0     0     0     1     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     0     0     0     0     1     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,26] [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37]
 [1,]     0     0     1     0     0     1     1     1     0     1     0     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     1     0     1     1     0     0     0     0     0     0     1
 [7,]     1     0     0     0     0     0     0     0     0     0     0     0
 [8,]     0     0     0     0     0     0     0     0     0     0     0     0
 [9,]     0     0     0     0     0     0     0     0     1     0     1     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,38] [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49]
 [1,]     0     1     0     0     0     0     0     1     0     0     1     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     0     0     0     0     0     0     0     0     1     0     0
 [4,]     0     0     0     0     0     0     0     0     0     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0     0
 [6,]     0     0     1     1     0     1     0     0     1     0     0     0
 [7,]     0     0     0     0     1     0     0     0     0     0     0     1
 [8,]     0     0     0     0     0     0     0     0     0     0     0     0
 [9,]     1     0     0     0     0     0     1     0     0     0     0     0
[10,]     0     0     0     0     0     0     0     0     0     0     0     0
      [,50] [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60]
 [1,]     0     0     0     1     0     0     1     0     0     0     0
 [2,]     0     0     0     0     0     0     0     0     0     0     0
 [3,]     0     1     0     0     0     0     0     0     0     0     0
 [4,]     0     0     0     0     1     0     0     1     0     0     0
 [5,]     0     0     0     0     0     0     0     0     0     0     0
 [6,]     1     0     1     0     0     1     0     0     0     1     0
 [7,]     0     0     0     0     0     0     0     0     1     0     0
 [8,]     0    

## Problema de la Mochila

#### Descripción:
TODO

### Mochila Simple

#### Descripción:
TODO

In [54]:
ReadSimpleKnapsack <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.integer()
    close(con)
    list(
        n = raw[1],
        capacity = raw[2] ,
        value = raw[seq(4, length(raw), by = 3)],
        weight = raw[seq(5, length(raw), by = 3)]
    ) %>%
    return()
}

#### Modelo:
TODO

In [55]:
KnapsackSimpleExact <- function(object, capacity) {
    
}

#### Heurísticas:
TODO

In [56]:
KnapsackSimpleGreedy <- function(p, ...) {
    return(Solve("max", p$value, matrix(p$weight, nrow = 1, byrow = TRUE), p$capacity, all.bin = TRUE, ...))
}

In [57]:
gen100.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen100_1.txt")

In [58]:
a <- KnapsackSimpleGreedy(gen100.1)
matrix(a$solution, ncol = gen100.1$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    0    1    1    1    0    0    0    0    0     0     1     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,] 1     0     0     0     0     0     0     0     0     0     0     0    
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,] 0     0     1     0     0     1     0     0     0     0     1     0    
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
[1,] 0     0     0     0     0     0     0     1     0     1     0     0    
     [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
[1,] 0     1     0     0     0     1     0     1     1     0     0     0    
     [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
[1,] 1     0     0     1     0     0     0     1     0     0     0     0    
     [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
[1,] 0     0     0     1     0     0     1     0     0     0     1     0    
     [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
[1,] 0     0     0     0     0     0     0     0     0     1     0     0    
     [,99] [,100]
[1,] 1     0

[1] 1753

### Mochila Múltiple

#### Descripción:
TODO

#### Modelo:
TODO

In [59]:
KnapsackMultipleExact <- function(p, m, ...) {
    conditions <- matrix(rep(0,(m + p$n) * p$n * m), 
                         nrow = m + p$n, ncol = p$n * m, byrow = TRUE)
    
    
    
    for(i in 1:m) {
        conditions[i, (i - 1) * p$n + 1:p$n] <- p$weight
    }
    for(i in (m + 1):(p$n + m)) {
        conditions[i, seq(i-m, p$n*m, by = p$n)] <- 1
    }

    return(Solve("max", rep(p$value, m), conditions, c(rep(p$capacity, m), rep(1, p$n)),
                 all.bin = TRUE, ...))
}
gen10.1 <- ReadSimpleKnapsack("./data/knapsack/simple/gen10_1.txt")
m <- 2
a <- KnapsackMultipleExact(gen10.1, m)
matrix(a$solution, ncol = gen10.1$n, nrow = m, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0    1    1    0    1    1    1    0    1    0    
[2,] 1    0    0    1    0    0    0    1    0    1

[1] 529

#### Heurísticas:
TODO

In [60]:
KnapsackMultipleGreedy <- function(object, capacity) {
    
}

### Mochila Multidimensional

#### Descripción:
TODO

In [61]:
ReadMultidimensionalKnapsack <- function(file.name) {
    con <- 
        file.name %>%
        file(open = "r")
    raw <- 
        con %>%
        readLines(warn = FALSE) %>% 
        strsplit("[[:blank:]]") %>%
        unlist() %>%
        as.double()
    close(con)
    list(n        = raw[1],
         m        = raw[2],
         objval   = raw[3],
         value    = raw[4:(raw[1]+ 3)],
         weight   = matrix(raw[(4 + raw[1]):(3 + raw[1] * (1 + raw[2]))], 
                           ncol = raw[1], byrow = TRUE),
         capacity = raw[(4 + raw[1] * (1 + raw[2]) ):length(raw)]
    ) %>%
    return()
}

#### Modelo:
TODO

In [62]:
KnapsackMultidimensionalExact <- function(p, ...) {    
    return(Solve("max", p$value, p$weight, p$capacity, all.bin = TRUE,...))
}

#### Heurísticas:
TODO

In [63]:
KnapsackMultidimensionalGreedy <- function(object, capacity) {
    
}

### Ejemplos

In [64]:
mknap1.2 <- ReadMultidimensionalKnapsack("./data/knapsack/multidimensional/mknap1_2.dat")

In [65]:
a <- KnapsackMultidimensionalExact(mknap1.2)
matrix(a$solution, ncol = mknap1.2$n, byrow = TRUE)
a$objval

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0    1    0    1    1    0    0    1    0    1

[1] 8706.1